import { Candidate, Election, Policy, PolicyStatus, PoliticalParty, ElectionType } from './types';

export const ELECTIONS: Election[] = [
  {
    id: 'election-2026',
    name: '2026 九合一選舉',
    shortName: '2026 選舉專區',
    startDate: '2025-06-01',
    endDate: '2027-01-31',
    electionDate: '2026-11-28',
    types: [
      ElectionType.MAYOR,
      ElectionType.COUNCILOR,
      ElectionType.TOWNSHIP_MAYOR,
      ElectionType.INDIGENOUS_DISTRICT_CHIEF,
      ElectionType.REPRESENTATIVE,
      ElectionType.INDIGENOUS_DISTRICT_REP,
      ElectionType.CHIEF,
    ],
  },
];

export const getElectionById = (id: string) => ELECTIONS.find(e => e.id === id);

export const getActiveElection = (): Election => {
  const today = new Date().toISOString().slice(0, 10);
  const active = ELECTIONS
    .filter(e => e.startDate <= today && today <= e.endDate)
    .sort((a, b) => a.electionDate.localeCompare(b.electionDate));
  return active[0] || ELECTIONS[0];
};

export const CANDIDATES: Candidate[] = [
  {
    id: 'c0',
    name: '前任高雄市長',
    party: PoliticalParty.KMT,
    electionType: ElectionType.MAYOR,
    position: '前高雄市長',
    region: '高雄市',
    avatarUrl: 'https://ui-avatars.com/api/?name=Han&background=0D8ABC&color=fff',
    electionIds: [],
    bio: '曾任高雄市長，推動路平專案與初期產業園區規劃。',
  },
  {
    id: 'c1',
    name: '蔣萬安',
    party: PoliticalParty.KMT,
    electionType: ElectionType.MAYOR,
    position: '台北市長',
    region: '台北市',
    avatarUrl: 'https://picsum.photos/200/200?random=1',
    electionIds: ['election-2026'],
    slogan: '台北隊，出發！讓世界看見台北',
    bio: '現任台北市長，致力於打造服務型政府，推動都更、交通與智慧城市建設。',
    education: ['美國賓州大學法學博士', '國立政治大學外交學系'],
    experience: ['第10屆立法委員', '萬澤外國法事務律師事務所律師']
  },
  {
    id: 'c2',
    name: '侯友宜',
    party: PoliticalParty.KMT,
    electionType: ElectionType.MAYOR,
    position: '新北市長',
    region: '新北市',
    avatarUrl: 'https://picsum.photos/200/200?random=2',
    electionIds: [], 
    slogan: '好好做事，團結共好',
    bio: '警察出身，強調執行力與行政中立，推動新北 2030 願景工程。',
    education: ['中央警察大學犯罪防治研究所博士'],
    experience: ['新北市副市長', '內政部警政署署長', '中央警察大學校長']
  },
  {
    id: 'c3',
    name: '陳其邁',
    party: PoliticalParty.DPP,
    electionType: ElectionType.MAYOR,
    position: '高雄市長',
    region: '高雄市',
    avatarUrl: 'https://picsum.photos/200/200?random=3',
    electionIds: [],
    slogan: '緊緊緊，兩年拚四年',
    bio: '棄醫從政，致力於高雄產業轉型，引進半導體產業鏈與推動亞灣區發展。',
    education: ['國立台灣大學公共衛生碩士', '中山醫學院醫學系'],
    experience: ['行政院副院長', '立法委員', '總統府副秘書長']
  },
  {
    id: 'c4',
    name: '高虹安',
    party: PoliticalParty.TPP,
    electionType: ElectionType.MAYOR,
    position: '新竹市長',
    region: '新竹市',
    avatarUrl: 'https://picsum.photos/200/200?random=4',
    electionIds: ['election-2026'],
    slogan: '新竹 UPGRADE，科技新未來',
    bio: '科技背景出身，強調數據治理與科學決策，致力解決新竹交通與教育問題。',
    education: ['美國辛辛那提大學機械工程博士', '國立台灣大學資訊工程碩士'],
    experience: ['立法委員', '鴻海集團工業大數據辦公室主任']
  },
  {
    id: 'c5',
    name: '王小明',
    party: PoliticalParty.DPP,
    electionType: ElectionType.MAYOR,
    position: '台北市長參選人',
    region: '台北市',
    avatarUrl: 'https://picsum.photos/200/200?random=5',
    electionIds: ['election-2026'],
    slogan: '翻轉台北，居住正義',
    bio: '長期關注居住正義與都市規劃的學者，主張大膽改革社宅政策與都市更新。',
    education: ['國立台灣大學建築與城鄉研究所博士'],
    experience: ['居住正義聯盟 理事長', '台北市都市計畫委員']
  },
  {
    id: 'c6',
    name: '林大華',
    party: PoliticalParty.IND,
    electionType: ElectionType.MAYOR,
    position: '新竹市長參選人',
    region: '新竹市',
    avatarUrl: 'https://picsum.photos/200/200?random=6',
    electionIds: ['election-2026'],
    slogan: '超越藍綠，交通先行',
    bio: '交通工程專家，無黨派包袱，承諾用專業解決竹科塞車問題。',
    education: ['國立交通大學交通運輸研究所碩士'],
    experience: ['新竹科學園區 交通顧問', '民間交通改革協會 發起人']
  },
  {
    id: 'c7',
    name: '張熱血',
    party: PoliticalParty.TPP,
    electionType: ElectionType.COUNCILOR,
    position: '台北市議員參選人',
    region: '台北市',
    subRegion: '中山大同區',
    avatarUrl: 'https://ui-avatars.com/api/?name=Chang&background=0ea5e9&color=fff',
    electionIds: ['election-2026'],
    slogan: '監督市政，絕不放水',
    bio: '專注於交通改善與舊城區再生，強力監督市府預算執行。',
    education: ['國立政治大學公共行政碩士'],
    experience: ['國會助理', '社區發展協會 理事']
  },
  {
    id: 'c8',
    name: '陳在地',
    party: PoliticalParty.IND,
    electionType: ElectionType.COUNCILOR,
    position: '新竹市議員參選人',
    region: '新竹市',
    subRegion: '東區',
    avatarUrl: 'https://ui-avatars.com/api/?name=Chen&background=64748b&color=fff',
    electionIds: ['election-2026'],
    slogan: '為了孩子，守護新竹',
    bio: '全職媽媽參政，最懂親子需求，主打公園改造與教育資源分配。',
    education: ['國立清華大學社會學碩士'],
    experience: ['家長會長', '親子共學團 團長']
  },
  {
    id: 'c9',
    name: '李里長',
    party: PoliticalParty.IND,
    electionType: ElectionType.CHIEF,
    position: '新竹市東區龍山里長參選人',
    region: '新竹市',
    subRegion: '東區龍山里',
    avatarUrl: 'https://ui-avatars.com/api/?name=Li&background=f59e0b&color=fff',
    electionIds: ['election-2026'],
    slogan: '路平燈亮水溝通，服務最貼心',
    bio: '在地服務 20 年，最了解里民需求，隨叫隨到。',
  },
  {
    id: 'c10',
    name: '楊文科',
    party: PoliticalParty.KMT,
    electionType: ElectionType.MAYOR,
    position: '新竹縣長',
    region: '新竹縣',
    avatarUrl: 'https://ui-avatars.com/api/?name=Yang&background=000095&color=fff',
    electionIds: ['election-2026'],
    slogan: '科技首都，幸福竹縣',
    bio: '現任新竹縣長，致力於AI智慧園區與交通建設。',
  },
  {
    id: 'c11',
    name: '鄭朝方',
    party: PoliticalParty.DPP,
    electionType: ElectionType.TOWNSHIP_MAYOR,
    position: '竹北市長',
    region: '新竹縣',
    subRegion: '竹北市',
    avatarUrl: 'https://ui-avatars.com/api/?name=Cheng&background=1B9431&color=fff',
    electionIds: ['election-2026'],
    slogan: '竹北進化，年輕活力',
    bio: '現任竹北市長，推動公園改造與藝文活動。',
  },
  {
    id: 'c12',
    name: '林小市民',
    party: PoliticalParty.TPP,
    electionType: ElectionType.REPRESENTATIVE,
    position: '竹北市民代表參選人',
    region: '新竹縣',
    subRegion: '竹北市',
    avatarUrl: 'https://ui-avatars.com/api/?name=Lin&background=28C7C7&color=fff',
    electionIds: ['election-2026'],
    slogan: '監督公所，看緊荷包',
  },
  {
    id: 'c13',
    name: '張里長',
    party: PoliticalParty.IND,
    electionType: ElectionType.CHIEF,
    position: '竹北市中興里長',
    region: '新竹縣',
    subRegion: '中興里',
    avatarUrl: 'https://ui-avatars.com/api/?name=Chang&background=777&color=fff',
    electionIds: ['election-2026'],
    slogan: '熱心服務，全年無休',
  },
  {
    id: 'c14',
    name: '林山水',
    party: PoliticalParty.IND,
    electionType: ElectionType.INDIGENOUS_DISTRICT_CHIEF,
    position: '烏來區長參選人',
    region: '新北市',
    subRegion: '烏來區',
    avatarUrl: 'https://ui-avatars.com/api/?name=Lin&background=059669&color=fff',
    electionIds: ['election-2026'],
    slogan: '守護泰雅文化，發展生態觀光',
    bio: '在地泰雅族人，致力於推動烏來溫泉與原民文化深度旅遊。',
  },
  {
    id: 'c15',
    name: '高勇士',
    party: PoliticalParty.IND,
    electionType: ElectionType.INDIGENOUS_DISTRICT_REP,
    position: '烏來區民代表參選人',
    region: '新北市',
    subRegion: '烏來區',
    avatarUrl: 'https://ui-avatars.com/api/?name=Kao&background=0d9488&color=fff',
    electionIds: ['election-2026'],
    slogan: '監督區政，為族人發聲',
  },
  {
    id: 'c16',
    name: '林議員',
    party: PoliticalParty.DPP,
    electionType: ElectionType.COUNCILOR,
    position: '高雄市議員',
    region: '高雄市',
    subRegion: '楠梓區',
    avatarUrl: 'https://ui-avatars.com/api/?name=Lin&background=1B9431&color=fff',
    electionIds: ['election-2026'],
    slogan: '嚴審預算，為民把關',
    bio: '連任兩屆高雄市議員，長期關注產業發展與勞工權益。',
  },
  {
    id: 'c17',
    name: '陳區長',
    party: PoliticalParty.DPP,
    electionType: ElectionType.TOWNSHIP_MAYOR,
    position: '楠梓區長',
    region: '高雄市',
    subRegion: '楠梓區',
    avatarUrl: 'https://ui-avatars.com/api/?name=Chen&background=0ea5e9&color=fff',
    electionIds: ['election-2026'],
    slogan: '楠梓起飛，產業共榮',
    bio: '現任楠梓區長，負責協調台積電設廠周邊基礎建設。',
  },
  {
    id: 'c18',
    name: '王里長',
    party: PoliticalParty.IND,
    electionType: ElectionType.CHIEF,
    position: '楠梓區援中里長',
    region: '高雄市',
    subRegion: '楠梓區援中里',
    avatarUrl: 'https://ui-avatars.com/api/?name=Wang&background=f59e0b&color=fff',
    electionIds: ['election-2026'],
    slogan: '守護家園，迎接發展',
    bio: '在地里長，協助居民因應台積電設廠帶來的生活變化。',
  }
];

export const POLICIES: Policy[] = [
  {
    id: 'p0',
    candidateId: 'c0',
    title: '和發產業園區規劃',
    description: '規劃南部產業用地，為製造業回流做準備。',
    category: 'Economy',
    status: PolicyStatus.ACHIEVED,
    proposedDate: '2019-05-01',
    lastUpdated: '2020-06-01',
    progress: 100,
    tags: ['產業', '園區'],
    logs: [
      { id: 'l0-1', date: '2019-05-01', event: '提出規劃' },
      { id: 'l0-2', date: '2020-01-15', event: '土地徵收完成' },
    ],
    relatedPolicyIds: ['p5']
  },
  {
    id: 'p1',
    candidateId: 'c1',
    title: '台北大建設 - 都更加速',
    description: '推動公辦都更降門檻，加速台北市老舊公寓改建速度，落實居住正義。',
    category: 'Urban Planning',
    status: PolicyStatus.IN_PROGRESS,
    proposedDate: '2022-11-01',
    lastUpdated: '2024-05-15',
    progress: 45,
    tags: ['都更', '居住正義'],
    aiAnalysis: 'AI 分析：目前法規修訂已通過一讀，但民眾整合意願仍是主要挑戰。預計 2024 下半年會有首批示範案動工。',
    logs: [
      { id: 'l1-1', date: '2022-11-01', event: '政見提出' },
      { id: 'l1-2', date: '2023-06-01', event: '成立都更專案辦公室' },
      { id: 'l1-3', date: '2024-03-15', event: '修法草案送交議會' },
    ]
  },
  {
    id: 'p2',
    candidateId: 'c1',
    title: '長照補助加碼',
    description: '台北市長照補助提高至每年 5 萬元，減輕家庭照顧者負擔。',
    category: 'Welfare',
    status: PolicyStatus.ACHIEVED,
    proposedDate: '2022-10-15',
    lastUpdated: '2023-12-01',
    progress: 100,
    tags: ['社福', '老人照護'],
    aiAnalysis: 'AI 分析：預算已於 2023 年底全數通過並開始發放，民眾滿意度高，執行率達 98%。',
    logs: [
      { id: 'l2-1', date: '2022-10-15', event: '政見提出' },
      { id: 'l2-2', date: '2023-01-20', event: '預算編列完成' },
      { id: 'l2-3', date: '2023-12-01', event: '正式開放申請' },
    ]
  },
  {
    id: 'p3',
    candidateId: 'c2',
    title: '2030 新北願景',
    description: '以三軸心、三曲線為核心，串聯北北基桃生活圈，打造國際化大都會。',
    category: 'Urban Planning',
    status: PolicyStatus.IN_PROGRESS,
    proposedDate: '2018-08-01',
    lastUpdated: '2024-04-10',
    progress: 60,
    tags: ['區域發展', '國際化'],
    logs: [
      { id: 'l3-1', date: '2018-08-01', event: '願景發布' },
      { id: 'l3-2', date: '2022-12-25', event: '第二任期續推' },
    ]
  },
  {
    id: 'p4',
    candidateId: 'c2',
    title: '三環六線捷運路網',
    description: '持續推動捷運建設，包含萬大線、三鶯線等，完善新北交通路網。',
    category: 'Traffic',
    status: PolicyStatus.IN_PROGRESS,
    proposedDate: '2018-06-01',
    lastUpdated: '2024-06-01',
    progress: 75,
    tags: ['交通', '捷運'],
    aiAnalysis: 'AI 分析：三鶯線進度超前，預計 2025 年完工。萬大線因缺工缺料問題稍微延後，目前正積極趕工中。',
    logs: [
      { id: 'l4-1', date: '2023-01-15', event: '安坑輕軌通車' },
      { id: 'l4-2', date: '2024-02-20', event: '三鶯線列車測試' },
    ]
  },
  {
    id: 'p5',
    candidateId: 'c3',
    title: '半導體 S 廊帶',
    description: '串聯南科、路竹、橋頭至楠梓，打造全球最完整的半導體產業聚落。',
    category: 'Economy',
    status: PolicyStatus.IN_PROGRESS,
    proposedDate: '2020-08-15',
    lastUpdated: '2024-06-15',
    progress: 80,
    tags: ['產業', '台積電'],
    aiAnalysis: 'AI 分析：台積電高雄廠進度順利，本案延續前任市府產業園區基礎，並成功招商台積電，帶動周邊供應鏈。',
    relatedPolicyIds: ['p0', 'p8', 'p9', 'p10'],
    logs: [
      { id: 'l5-1', date: '2021-08-01', event: '台積電宣布設廠' },
      { id: 'l5-2', date: '2024-01-18', event: '2奈米廠動土' },
    ]
  },
  {
    id: 'p8',
    candidateId: 'c16',
    title: '半導體 S 廊帶預算審查',
    description: '嚴格審查台積電設廠相關市府配套預算，確保公帑用在刀口上，杜絕浮編與虛報。',
    category: 'Economy',
    status: PolicyStatus.IN_PROGRESS,
    proposedDate: '2022-03-10',
    lastUpdated: '2024-08-01',
    progress: 65,
    tags: ['產業', '台積電', '預算監督'],
    aiAnalysis: 'AI 分析：議員質詢紀錄顯示已針對道路拓寬、汙水處理等配套預算提出 12 次專案報告要求，有效提升預算透明度。',
    relatedPolicyIds: ['p5'],
    logs: [
      { id: 'l5c-1', date: '2022-03-10', event: '提案要求 S 廊帶預算專案報告' },
      { id: 'l5c-2', date: '2023-06-15', event: '質詢道路拓寬經費流向' },
      { id: 'l5c-3', date: '2024-08-01', event: '要求公開台積電周邊建設決算' },
    ]
  },
  {
    id: 'p9',
    candidateId: 'c17',
    title: '楠梓園區周邊基礎建設',
    description: '執行台積電設廠周邊道路拓寬、排水系統升級、公共運輸接駁規劃等基礎建設。',
    category: 'Economy',
    status: PolicyStatus.IN_PROGRESS,
    proposedDate: '2022-06-01',
    lastUpdated: '2024-10-15',
    progress: 55,
    tags: ['產業', '台積電', '基礎建設'],
    aiAnalysis: 'AI 分析：楠梓區公所已完成 3 條聯外道路拓寬，汙水處理廠擴建中，但居民反映施工噪音與交通管制影響生活。',
    relatedPolicyIds: ['p5'],
    logs: [
      { id: 'l5t-1', date: '2022-06-01', event: '啟動楠梓園區周邊道路評估' },
      { id: 'l5t-2', date: '2023-04-20', event: '後勁路拓寬工程動工' },
      { id: 'l5t-3', date: '2024-02-10', event: '汙水處理廠擴建案核定' },
      { id: 'l5t-4', date: '2024-10-15', event: '接駁公車路線試營運' },
    ]
  },
  {
    id: 'p10',
    candidateId: 'c18',
    title: '援中里居民安置與生活品質維護',
    description: '協助因台積電設廠受影響的援中里居民處理噪音、交通與環境問題，爭取合理補償。',
    category: 'Economy',
    status: PolicyStatus.PROPOSED,
    proposedDate: '2023-01-15',
    lastUpdated: '2024-11-01',
    progress: 40,
    tags: ['產業', '台積電', '居民權益'],
    aiAnalysis: 'AI 分析：里長已召開 8 次里民說明會，成功爭取施工時段限制與臨時停車空間，但長期環境影響評估仍待追蹤。',
    relatedPolicyIds: ['p5'],
    logs: [
      { id: 'l5ch-1', date: '2023-01-15', event: '召開第一次里民說明會' },
      { id: 'l5ch-2', date: '2023-09-01', event: '爭取施工噪音時段限制' },
      { id: 'l5ch-3', date: '2024-05-20', event: '協調臨時停車空間' },
      { id: 'l5ch-4', date: '2024-11-01', event: '提出長期環境監測訴求' },
    ]
  },
  {
    id: 'p6',
    candidateId: 'c4',
    title: '0 到 6 歲市府養',
    description: '加碼托育補助，凍卵補助，打造友善生育城市。',
    category: 'Welfare',
    status: PolicyStatus.PROPOSED,
    proposedDate: '2022-09-01',
    lastUpdated: '2024-03-01',
    progress: 30,
    tags: ['生育', '補助'],
    aiAnalysis: 'AI 分析：凍卵補助已於 2023 年試辦，但全面性的「市府養」預算龐大，目前採分階段實施，財源籌措是關鍵。',
    logs: [
      { id: 'l6-1', date: '2023-05-11', event: '凍卵補助計畫啟動' },
    ]
  },
  {
    id: 'p7',
    candidateId: 'c4',
    title: '智慧交通改善園區塞車',
    description: '利用 AI 號誌控制與大數據分析，紓解新竹科學園區周邊交通壅塞。',
    category: 'Traffic',
    status: PolicyStatus.STALLED,
    proposedDate: '2022-09-10',
    lastUpdated: '2024-05-20',
    progress: 20,
    tags: ['交通', '智慧城市'],
    aiAnalysis: 'AI 分析：雖然導入智慧號誌，但因園區上班車流量過大，硬體道路拓寬困難，民眾感受改善有限，目前計畫重新評估中。',
    logs: [
      { id: 'l7-1', date: '2023-03-01', event: '慈雲路智慧號誌測試' },
      { id: 'l7-2', date: '2024-05-01', event: '議會質詢成效不彰' },
    ]
  },
  {
    id: 'cp1',
    candidateId: 'c1',
    title: '2026 願景：台北元宇宙園區',
    description: '運用區塊鏈與 VR 技術，打造虛擬台北，促進數位經濟發展。',
    category: 'Economy',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-06-01',
    lastUpdated: '2025-06-01',
    progress: 0,
    tags: ['元宇宙', '數位經濟'],
    logs: [{ id: 'lcp1', date: '2025-06-01', event: '競選承諾發布' }],
    supportCount: 12500,
    aiAnalysis: 'AI 預測：此政見極具前瞻性，但需評估硬體普及率與法規適用性。年輕選民支持度較高。',
  },
  {
    id: 'cp5',
    candidateId: 'c1',
    title: '台北科技走廊計畫',
    description: '串聯內科、南軟至北士科，打造首都科技金三角，吸引國際大廠研發中心進駐。',
    category: 'Economy',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-07-10',
    lastUpdated: '2025-07-10',
    progress: 0,
    tags: ['科技', '產業發展'],
    logs: [{ id: 'lcp5', date: '2025-07-10', event: '競選承諾發布' }],
    supportCount: 15600,
    aiAnalysis: 'AI 預測：延續性政策的擴大版，對產業界有正面激勵效果，需注意交通配套。',
  },
  {
    id: 'cp2',
    candidateId: 'c5',
    title: '社宅租金全面八折',
    description: '重新檢視社宅定價公式，承諾當選後全面調降市有社宅租金至市價八折以下。',
    category: 'Welfare',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-05-20',
    lastUpdated: '2025-05-20',
    progress: 0,
    tags: ['居住正義', '租屋補貼'],
    logs: [{ id: 'lcp2', date: '2025-05-20', event: '競選承諾發布' }],
    supportCount: 34200,
    aiAnalysis: 'AI 預測：高房價議題下的強力吸票機，但需詳細說明財源替代方案，否則易流於民粹。',
  },
  {
    id: 'cp4',
    candidateId: 'c5',
    title: '國中小營養午餐免費',
    description: '全額補助公立國中小營養午餐費用，減輕家長負擔，確保學童營養均衡。',
    category: 'Education',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-06-15',
    lastUpdated: '2025-06-15',
    progress: 0,
    tags: ['教育', '營養午餐'],
    logs: [{ id: 'lcp4', date: '2025-06-15', event: '競選承諾發布' }],
    supportCount: 21000,
    aiAnalysis: 'AI 預測：家長族群支持度極高，但需考量長期財政負擔與排擠效應。',
  },
  {
    id: 'cp3',
    candidateId: 'c6',
    title: '新竹輕軌立即動工',
    description: '解決多年延宕問題，承諾上任半年內完成土地徵收，一年內動工。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-07-01',
    lastUpdated: '2025-07-01',
    progress: 0,
    tags: ['交通', '輕軌'],
    logs: [{ id: 'lcp3', date: '2025-07-01', event: '競選承諾發布' }],
    supportCount: 8900,
    aiAnalysis: 'AI 預測：針對性極強的政見，直接挑戰現任者的執行力痛點。',
  },
  {
    id: 'cp_c7_1',
    candidateId: 'c7',
    title: '捷運大同線增設出口',
    description: '爭取捷運站體增設無障礙出口，方便長者與輪椅族進出。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-08-01',
    lastUpdated: '2025-08-01',
    progress: 0,
    tags: ['交通', '無障礙'],
    logs: [{ id: 'l_cp_c7_1', date: '2025-08-01', event: '競選承諾發布' }],
    supportCount: 1200,
  },
  {
    id: 'cp_c8_1',
    candidateId: 'c8',
    title: '東區公園全面遊具更新',
    description: '淘汰罐頭遊具，打造共融式遊戲場，讓孩子玩得開心又安全。',
    category: 'Welfare',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-08-10',
    lastUpdated: '2025-08-10',
    progress: 0,
    tags: ['親子', '公園'],
    logs: [{ id: 'l_cp_c8_1', date: '2025-08-10', event: '競選承諾發布' }],
    supportCount: 2500,
  },
  {
    id: 'stack_mayor_1',
    candidateId: 'c4',
    title: '大新竹智慧交通網 2.0',
    description: '升級全市交通號誌控制系統，導入 AI 預判車流，並建立大新竹交通行控中心。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-06-20',
    lastUpdated: '2025-06-20',
    progress: 0,
    tags: ['交通', '智慧城市', '新竹交通'],
    logs: [{ id: 'l_stack_m1', date: '2025-06-20', event: '發布 2.0 計畫' }],
    supportCount: 4500,
  },
  {
    id: 'stack_counc_1',
    candidateId: 'c8',
    title: '嚴審智慧交通預算，杜絕無效號誌',
    description: '強力監督市府智慧交通標案，要求廠商提出具體車流改善數據，拒絕裝飾性工程。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-07-05',
    lastUpdated: '2025-07-05',
    progress: 0,
    tags: ['交通', '財政紀律', '新竹交通'],
    logs: [{ id: 'l_stack_c1', date: '2025-07-05', event: '發布質詢重點' }],
    supportCount: 1800,
  },
  {
    id: 'stack_chief_1',
    candidateId: 'c9',
    title: '爭取龍山路口增設智慧感應號誌',
    description: '本里龍山路口車禍頻傳，將依據市府智慧交通計畫，爭取優先安裝感應式紅綠燈。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-07-15',
    lastUpdated: '2025-07-15',
    progress: 0,
    tags: ['交通', '社區安全', '新竹交通'],
    logs: [{ id: 'l_stack_ch1', date: '2025-07-15', event: '里民大會提案' }],
    supportCount: 650,
  },
  {
    id: 'p_hc_mayor_1',
    candidateId: 'c10',
    title: '大新竹輕軌藍線延伸竹北',
    description: '爭取輕軌跨越頭前溪，串聯竹科與竹北生活圈。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-06-01',
    lastUpdated: '2025-06-01',
    progress: 0,
    tags: ['交通', '輕軌', '竹北生活圈'],
    logs: [{ id: 'l_hc_m1', date: '2025-06-01', event: '提出規劃' }],
    supportCount: 8000,
  },
  {
    id: 'p_hc_tm_1',
    candidateId: 'c11',
    title: '配合輕軌規劃站點接駁車',
    description: '於市區規劃 YouBike 與免費接駁巴士，串聯輕軌預定站點。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-06-15',
    lastUpdated: '2025-06-15',
    progress: 0,
    tags: ['交通', '接駁', '竹北生活圈'],
    logs: [{ id: 'l_hc_tm1', date: '2025-06-15', event: '發布接駁計畫' }],
    supportCount: 4200,
  },
  {
    id: 'p_hc_rep_1',
    candidateId: 'c12',
    title: '要求接駁車路線繞經舊市區',
    description: '監督公所接駁計畫，確保舊市區長者也能享受大眾運輸便利。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-07-01',
    lastUpdated: '2025-07-01',
    progress: 0,
    tags: ['交通', '公平正義', '竹北生活圈'],
    logs: [{ id: 'l_hc_rep1', date: '2025-07-01', event: '代表會質詢' }],
    supportCount: 1500,
  },
  {
    id: 'p_hc_chief_1',
    candidateId: 'c13',
    title: '爭取中興里設 YouBike 站',
    description: '本里人口密集，爭取於活動中心前設置 YouBike 2.0 站點。',
    category: 'Traffic',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-07-10',
    lastUpdated: '2025-07-10',
    progress: 0,
    tags: ['交通', '便民', '竹北生活圈'],
    logs: [{ id: 'l_hc_chief1', date: '2025-07-10', event: '連署提案' }],
    supportCount: 600,
  },
  {
    id: 'p_wulai_chief_1',
    candidateId: 'c14',
    title: '烏來溫泉觀光升級計畫',
    description: '結合泰雅文化與生態導覽，打造國際級溫泉觀光品牌。',
    category: 'Economy',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-06-25',
    lastUpdated: '2025-06-25',
    progress: 0,
    tags: ['觀光', '原民文化', '烏來觀光'],
    logs: [{ id: 'l_wulai_chief_1', date: '2025-06-25', event: '政見發表' }],
    supportCount: 3000,
  },
  {
    id: 'p_wulai_rep_1',
    candidateId: 'c15',
    title: '爭取溫泉區收益回饋族人',
    description: '要求觀光收益應有固定比例回饋部落建設與長者照護。',
    category: 'Welfare',
    status: PolicyStatus.CAMPAIGN,
    proposedDate: '2025-07-01',
    lastUpdated: '2025-07-01',
    progress: 0,
    tags: ['權益', '社福', '烏來觀光'],
    logs: [{ id: 'l_wulai_rep_1', date: '2025-07-01', event: '代表會質詢' }],
    supportCount: 1200,
  }
];

export const CATEGORIES = ['Urban Planning', 'Welfare', 'Traffic', 'Economy', 'Education', 'Environment'];
export const LOCATIONS = ['台北市', '新北市', '高雄市', '新竹市', '台中市', '台南市', '新竹縣'];