-- 日本站「自動發現選舉」：任期満了快到、卻沒有對應選舉的團體 → 派 election_discovery 任務（policy-jp #41 ③、PR②）
-- ============================================================
--
-- 前提：20261009110000_policy_jp_dispatch.sql（派工機制）。
--
-- 原則（policy-jp #39 的 10/08 定案）：**程式不產生選舉資料。** 這支只找缺口、派任務；代理附選管的告示交件，
--   共識後才寫進 elections（落庫是下一個 PR）。
-- 交件型別（policy-jp #41 待定 C 的預設，等主線拍板）：
--   * 查到日程 → contribution_type = election（新型別，照「加新型別要清點四處」：本檔的 CHECK、jp/contribution-schema.ts、jp/consensus.ts、日本站 skill.md）
--   * 選管還沒公布 → no_change，outcome = not_found，checked_urls 放看過的選管頁（正見既有的結果值，不另發明）
-- 新增一支派工臂照正見的三處（CLAUDE.md「新增一支派工臂要三處一起加」）：總表多一行 UNION 分支、activity_arm_names() 多一個名字、
--   activity_rules 種一條規則。總表與名單是 110000 的版本加一行，守門 policy-jp-election-discovery.test.ts 做替換比對。
--
-- 缺口的來源：總務省「地方公共団体の議会の議員及び長の任期満了に関する調」（每年 11/1 現在）。存成 term_expirations：
--   * 每一列掛出處（source_id NOT NULL → sources）；
--   * 只當缺口的來源，任何函式都不從它建 elections 列（測試檢查 seed 後 elections 仍是 0 列）。
--   資料由 20261009131000_policy_jp_term_expirations_r08.sql 匯入（policy-jp 的 scripts/fetch/term-expirations-sql.mjs 產生）。
--
-- 範圍：投票日 2027-01-01 以後（params.scope_from）。任期満了選舉在満了日前 30 天內投票（公職選挙法 33 条），
--   所以満了日 T 的投票日在 [T−30, T−1]。T−1 ≥ scope_from 才算缺口；T−30 < scope_from 的（投票日可能在 2026 年）
--   include_uncertain=true 時也開，請代理確認投票日（是 2026 年也照樣交 election——那仍是一場真的選舉）。
-- 件數上限（docs/PLAN-task-activation.md 6.3 的 params.cap）：50 件，依満了日由早到晚（最急的先）。正見沒有讀 cap 的臂，
--   所以做在臂裡（ORDER BY + LIMIT），總表骨架不動。

-- ------------------------------------------------------------
-- 1. 缺口的來源：任期満了日（總務省調查的快照）
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.term_expirations (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lg_code       TEXT NOT NULL CHECK (policy_jp.lg_code_valid(lg_code)),
  pref_name     TEXT NOT NULL,
  lg_name       TEXT NOT NULL,
  office_kind   TEXT NOT NULL CHECK (office_kind IN ('head', 'assembly')),
  election_type TEXT NOT NULL CHECK (election_type IN ('governor', 'mayor', 'ward_mayor', 'town_mayor', 'pref_assembly', 'muni_assembly')),
  term_end      DATE NOT NULL,
  head_name     TEXT,
  as_of         DATE NOT NULL,
  source_id     BIGINT NOT NULL REFERENCES policy_jp.sources(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT term_expirations_one_per_snapshot UNIQUE (lg_code, office_kind, as_of),
  CONSTRAINT term_expirations_head_name CHECK (office_kind = 'head' OR head_name IS NULL),
  CONSTRAINT term_expirations_kind_type CHECK (
    (office_kind = 'head') = (election_type IN ('governor', 'mayor', 'ward_mayor', 'town_mayor')))
);
CREATE INDEX IF NOT EXISTS term_expirations_term_end_idx ON policy_jp.term_expirations (term_end);
COMMENT ON TABLE policy_jp.term_expirations IS
  '任期満了日（總務省「任期満了に関する調」的快照，as_of＝調查基準日）。只當缺口（election_discovery）的來源，'
  '不從這裡建 elections 列。每列 source_id 必填。lg_code 不對 local_governments 設外鍵（團體表還沒匯入也能出缺口，所以名稱一起存）';

ALTER TABLE policy_jp.term_expirations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read" ON policy_jp.term_expirations;
CREATE POLICY "Public read" ON policy_jp.term_expirations FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON policy_jp.term_expirations TO anon, authenticated;
GRANT ALL ON policy_jp.term_expirations TO service_role;

-- ------------------------------------------------------------
-- 2. 交件型別 election（查到的選舉日程；落庫是下一個 PR）
-- ------------------------------------------------------------
ALTER TABLE policy_jp.contributions DROP CONSTRAINT IF EXISTS contributions_contribution_type_check;
ALTER TABLE policy_jp.contributions ADD CONSTRAINT contributions_contribution_type_check
  CHECK (contribution_type IN ('no_change', 'task_suggestion', 'correction', 'election'));

-- ------------------------------------------------------------
-- 3. 臂：任期快満了，卻沒有對應的選舉
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION policy_jp.contribution_auto_tasks_election_discovery()
RETURNS TABLE (task_id TEXT, task_type TEXT, target JSONB, what_we_need TEXT, hint_sources TEXT[], reward INTEGER, region TEXT)
LANGUAGE sql STABLE SET search_path = policy_jp, pg_temp AS $$
  WITH p AS (
    SELECT (r.params->>'scope_from')::DATE AS scope_from,
           (r.params->>'lead_days')::INTEGER AS lead_days,
           COALESCE((r.params->>'include_uncertain')::BOOLEAN, true) AS include_uncertain,
           (r.params->>'cap')::INTEGER AS cap,
           policy_jp.activity_today() AS today
      FROM policy_jp.activity_rules r
     WHERE r.activity = 'election_discovery' AND r.enabled
     ORDER BY r.id LIMIT 1
  ),
  latest AS (
    SELECT DISTINCT ON (t.lg_code, t.office_kind) t.* FROM policy_jp.term_expirations t ORDER BY t.lg_code, t.office_kind, t.as_of DESC
  ),
  gaps AS (
    SELECT t.*, p.scope_from FROM latest t CROSS JOIN p
     WHERE p.scope_from IS NOT NULL AND p.lead_days IS NOT NULL AND p.cap IS NOT NULL
       AND t.term_end - 1 >= p.scope_from
       AND (p.include_uncertain OR t.term_end - 30 >= p.scope_from)
       AND t.term_end - p.lead_days <= p.today
       AND t.term_end + 60 >= p.today
       AND NOT EXISTS (
         SELECT 1 FROM policy_jp.elections e
          WHERE e.lg_code = t.lg_code AND e.election_type = t.election_type AND e.review_status <> 'rejected'
            AND e.election_date BETWEEN t.term_end - 120 AND t.term_end + 60)
     ORDER BY t.term_end, t.lg_code, t.office_kind
     LIMIT (SELECT cap FROM p)
  )
  SELECT 'auto:election_discovery:' || g.term_end || ':' || g.lg_code || ':' || g.office_kind, 'election_discovery',
         jsonb_build_object('lg_code', g.lg_code, 'pref_name', g.pref_name, 'lg_name', g.lg_name,
                            'office_kind', g.office_kind, 'election_type', g.election_type, 'term_end', g.term_end,
                            'vote_window_from', g.term_end - 30, 'vote_window_until', g.term_end - 1,
                            'certainly_in_scope', (g.term_end - 30 >= g.scope_from), 'scope_from', g.scope_from,
                            'term_source_id', g.source_id, 'term_as_of', g.as_of),
         g.lg_name || 'の' || CASE WHEN g.office_kind = 'head' THEN '長' ELSE '議会議員' END || 'の任期は ' || g.term_end || ' に満了します（総務省「任期満了に関する調」' || g.as_of || ' 現在）。'
           || 'この任期満了による選挙の告示日・投票日を、' || g.pref_name || 'または' || g.lg_name || 'の選挙管理委員会の告示・お知らせで確かめてください。'
           || '公表済みなら contribution_type=election（lg_code・election_type・election_reason・election_date・notice_date、出典は選管の告示）。'
           || 'まだ公表されていなければ contribution_type=no_change、outcome=not_found、checked_urls に見た選管のページを入れてください。'
           || '辞職などで任期が変わっていた場合も、実際の選挙日程を election で回報してください。',
         ARRAY[g.pref_name || '選挙管理委員会', g.lg_name || '選挙管理委員会', '総務省 任期満了に関する調']::TEXT[], 2, g.pref_name
    FROM gaps g
$$;
COMMENT ON FUNCTION policy_jp.contribution_auto_tasks_election_discovery IS
  '任期満了日（term_expirations）が近いのに対応する選挙がない団体 → election_discovery 任務。規則 election_discovery の params（scope_from、lead_days、include_uncertain、cap）を読む';

-- ------------------------------------------------------------
-- 4. 臂名清單與總表：110000 的版本各多一個名字／一行分支（其餘一字不改；守門做替換比對）
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION policy_jp.activity_arm_names() RETURNS TEXT[]
LANGUAGE sql IMMUTABLE SET search_path = policy_jp, pg_temp AS $$
  SELECT ARRAY[
    'manual_visitor',
    'manual_open',
    'election_discovery'
  ]::TEXT[]
$$;

CREATE OR REPLACE FUNCTION policy_jp.contribution_auto_tasks_arms()
RETURNS TABLE (task_id TEXT, task_type TEXT, target JSONB, what_we_need TEXT, hint_sources TEXT[], reward INTEGER, region TEXT, arm TEXT, opened_by JSONB)
LANGUAGE sql STABLE AS $$
  WITH tagged AS (
  SELECT 'manual_visitor' AS arm, t.* FROM policy_jp.contribution_auto_tasks_manual(true) t
  UNION ALL SELECT 'manual_open' AS arm, t.* FROM policy_jp.contribution_auto_tasks_manual(false) t
  UNION ALL SELECT 'election_discovery' AS arm, t.* FROM policy_jp.contribution_auto_tasks_election_discovery() t
       ),
       -- 每一列的選舉與職位（target 裡沒有就是「不屬於任何選舉」）；規則只對「臂×選舉×職位」各問一次，不是每一列問一次
       keyed AS (
  SELECT g.*, policy_jp.election_id_or_null(g.target->>'election_id') AS eid, NULLIF(g.target->>'election_type', '') AS etype FROM tagged g
       ),
       opened AS (
  SELECT k.arm, k.eid, k.etype, o.source, o.rule_id, o.override_id, o.milestone_kind, o.milestone_on_date, o.expected_open_on, o.open_until
    FROM (SELECT x.arm, x.eid, x.etype
            FROM (SELECT DISTINCT d.arm, d.eid, d.etype FROM keyed d OFFSET 0) x
           WHERE policy_jp.activity_require_rule(x.arm) OFFSET 0) k
    LEFT JOIN LATERAL (  -- LEFT：窗口關著的組也留下來（o.source 是 NULL），旗標 gap.arms_all 開著時 seed 要看它們
      SELECT * FROM policy_jp.activity_open(k.arm, k.eid, k.etype)
       ORDER BY expected_open_on NULLS LAST, rule_id NULLS LAST, override_id NULLS LAST LIMIT 1
    ) o ON true
       )
  SELECT g.task_id, g.task_type, g.target, g.what_we_need, g.hint_sources, g.reward, g.region, g.arm,
         CASE WHEN o.source IS NOT NULL THEN jsonb_strip_nulls(jsonb_build_object(
           'basis', o.source, 'arm', g.arm, 'rule_id', o.rule_id, 'override_id', o.override_id, 'election_id', g.eid,
           'milestone_kind', o.milestone_kind, 'milestone_on_date', o.milestone_on_date, 'expected_open_on', o.expected_open_on, 'open_until', o.open_until)) END AS opened_by
    FROM keyed g
    JOIN opened o ON o.arm = g.arm AND COALESCE(o.eid, '') = COALESCE(g.eid, '') AND COALESCE(o.etype, '') = COALESCE(g.etype, '')
   WHERE (o.source IS NOT NULL OR (SELECT current_setting('gap.arms_all', true) = 'on'))  -- 旗標沒設（預設）＝只回開著的列；一個 InitPlan，不是每列算
$$;

-- ------------------------------------------------------------
-- 5. 規則（照正見「新增一支臂」：規則直接種；cap 等參數放 params）
-- ------------------------------------------------------------
INSERT INTO policy_jp.activity_rules (activity, window_kind, min_status, params, note)
SELECT 'election_discovery', 'always', 'announced',
       '{"cap":50,"lead_days":180,"scope_from":"2027-01-01","include_uncertain":true}'::JSONB,
       '任期満了前 180 天起（在臂裡判斷）：沒有對應選舉的團體，到選管確認日程。投票日 2027-01-01 以後；同時開啟最多 50 件，満了日早的先'
 WHERE NOT EXISTS (SELECT 1 FROM policy_jp.activity_rules r WHERE r.activity = 'election_discovery' AND r.priority IS NULL);

-- ------------------------------------------------------------
-- 6. 權限與自我檢查（同 110000：新函式預設對 PUBLIC 可執行，要明寫收回）
-- ------------------------------------------------------------
REVOKE EXECUTE ON FUNCTION policy_jp.contribution_auto_tasks_election_discovery() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION policy_jp.contribution_auto_tasks_arms() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION policy_jp.activity_arm_names() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION policy_jp.contribution_auto_tasks_election_discovery(), policy_jp.contribution_auto_tasks_arms(),
  policy_jp.activity_arm_names() TO service_role;

DO $$
DECLARE bad TEXT;
BEGIN
  IF NOT (SELECT c.relrowsecurity FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
           WHERE n.nspname = 'policy_jp' AND c.relname = 'term_expirations') THEN
    RAISE EXCEPTION 'policy_jp.term_expirations 沒開 RLS';
  END IF;
  SELECT string_agg(a.arm, ', ') INTO bad
    FROM unnest(policy_jp.activity_arm_names()) AS a(arm)
   WHERE NOT EXISTS (SELECT 1 FROM policy_jp.activity_rules r WHERE r.activity = a.arm);
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'policy_jp：這些派工臂沒有規則：%', bad; END IF;
  IF NOT EXISTS (SELECT 1 FROM policy_jp.activity_rules r WHERE r.activity = 'election_discovery' AND r.enabled
                  AND r.params ? 'cap' AND r.params ? 'lead_days' AND r.params ? 'scope_from') THEN
    RAISE EXCEPTION 'policy_jp：election_discovery 的規則缺 cap／lead_days／scope_from（臂會整支回 0 列＝無聲消失）';
  END IF;
  IF has_function_privilege('anon', 'policy_jp.contribution_auto_tasks_election_discovery()', 'EXECUTE') THEN
    RAISE EXCEPTION 'policy_jp：派工臂不該給 anon 執行';
  END IF;
END
$$;

NOTIFY pgrst, 'reload schema';
