-- 日本站（政策の系譜）第一批資料表：policy_jp schema（policy-jp #39 ①）
-- ============================================================
--
-- 這支只在 policy_jp 裡建表，不碰 public、ditrust，不碰正見既有的函式、cron、Edge Function。
-- 前提：20261008195000_policy_jp_schema.sql（#479）已建好空的 policy_jp 與基本權限
--       （USAGE 給 anon／authenticated／service_role；service_role 對之後的物件有完整權限；函式預設不給 PUBLIC 執行）。
--
-- 形狀：照日本站 docs/SCHEMA.md v0.7，並一次對齊正見現在的寫法（issue #39 ① 的 11 點）：
--   1. 出處改用 source_refs（source_id、target_table、target_id、role、origin），各表不再放 source_ids 陣列（同正見 #354／#404／#416）。
--      參選狀態的出處（SCHEMA 的 status_source_ids）用 target_table='politician_election_status' 跟參選本身的出處分開。
--      查核紀錄的依據（SCHEMA 的 evidence_source_ids）用 target_table='reviews'。
--   2. sources：url UNIQUE、加 origin、fetched_at 可空；source_kind 保留日本的六個值（見欄位註解）。
--   3. self_evidence 只收 linked_by_official、mutual_link（拿掉 platform_verified，同正見協議 1.62.0：社群貼文不能標 self）。
--   4. politician_offices 加 end_reason、end_basis（有卸任日兩欄都必填）、politician_election_id。
--   5. politician_elections 加 withdrawn_after_filing、party_basis；狀態欄位叫 candidacy_status（六個值）。
--   6. election_districts 加 seats_basis（law／notice）；is_uncontested 放在選舉區這一層（elections 不放）。
--   7. elections：election_reason 加 rerun；加 level、jurisdiction、timezone；name、lineage_id 進表；candidates_count 不存（要時算）；
--      字串 id＝正見的 election_key（建立後不改）。
--   8. politician_careers：加 id；sort_order（SCHEMA 樣品的 seq 改名）；(politician_id, kind, text) 不重複。
--   9. parties：加 short_name、predecessor_id、note。
--  10. lineages 加 level、lg_code 可空；新表 lineage_participants、lineage_links（同正見 #378）；handovers 加 source_locator。
--  11. 不建得票數、得票率的欄位，也不建票數備份表（日本站規矩）。檔尾的檢查擋住任何 vote／得票 字樣的欄位。
--
-- 權限：
--   * 每張表都 ENABLE ROW LEVEL SECURITY。
--   * anon、authenticated：逐表 GRANT SELECT，沒有任何 INSERT／UPDATE／DELETE 權限，也沒有寫入用的 policy。
--     有 review_status 的表，公開讀只看得到 published（SCHEMA：畫面只顯示 published）；參照用的表（団体、政黨、會派、出處…）全部可讀。
--   * 寫入一律由 service_role（Edge Function／之後的寫入函式）做；service_role 在 Supabase 有 BYPASSRLS，
--     表的權限來自 #479 的 ALTER DEFAULT PRIVILEGES。這一批沒有寫入函式（② 派工機制、③ 的任務落庫時才加）。
--   * 選舉列一律經任務回報建立（③：找缺口→派 election_discovery→代理附官方出處回報→共識才寫入），程式不推算、不自動建列；
--     所以 elections 沒有「推定／確定」之類給系統推算用的欄位。
--   * 檔尾的檢查：policy_jp 裡沒開 RLS 的表、anon／authenticated 有寫入權限的表，都會讓這支 migration 失敗。
--
-- id：日本站的資料目前是 JSON 樣品，id 都是字串（elections 的 id 規則見表註解），這裡照用 TEXT；
--     只有 sources 照正見用 BIGINT（source_refs.source_id 要跟正見同型別）。
-- 守門：supabase/functions/_shared/policy-jp-tables.test.ts（PGlite 實跑這支 migration：權限、RLS、CHECK、沒有票數欄位）。

-- ------------------------------------------------------------
-- 0. 共用函式
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION policy_jp.touch_updated_at() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = policy_jp, pg_temp AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- 全国地方公共団体コード（6 碼）的檢查碼：前 5 碼乘 6,5,4,3,2，總和除以 11 的餘數 r，檢查碼＝(11−r) mod 10（總務省代碼表 1,965 筆全部吻合）
CREATE OR REPLACE FUNCTION policy_jp.lg_code_valid(p_code TEXT) RETURNS BOOLEAN
LANGUAGE sql IMMUTABLE SET search_path = policy_jp, pg_temp AS $$
  SELECT p_code ~ '^[0-9]{6}$'
     AND (11 - ((substr(p_code, 1, 1)::INT * 6 + substr(p_code, 2, 1)::INT * 5 + substr(p_code, 3, 1)::INT * 4
                + substr(p_code, 4, 1)::INT * 3 + substr(p_code, 5, 1)::INT * 2) % 11)) % 10 = substr(p_code, 6, 1)::INT
$$;

-- 層級（正見 PLAN-task-activation 第 6 節的共用詞彙）：國政＝national、都道府県（知事・県議）＝regional、市区町村＝local
CREATE OR REPLACE FUNCTION policy_jp.election_level(p_election_type TEXT) RETURNS TEXT
LANGUAGE sql IMMUTABLE SET search_path = policy_jp, pg_temp AS $$
  SELECT CASE
           WHEN p_election_type IN ('national_lower', 'national_upper') THEN 'national'
           WHEN p_election_type IN ('governor', 'pref_assembly') THEN 'regional'
           WHEN p_election_type IN ('mayor', 'ward_mayor', 'town_mayor', 'muni_assembly') THEN 'local'
         END
$$;

GRANT EXECUTE ON FUNCTION policy_jp.lg_code_valid(TEXT), policy_jp.election_level(TEXT) TO anon, authenticated;

-- ------------------------------------------------------------
-- 1. 出處
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.sources (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url            TEXT NOT NULL UNIQUE,
  title          TEXT,
  publisher      TEXT,
  source_kind    TEXT NOT NULL DEFAULT 'other'
                 CHECK (source_kind IN ('official', 'self', 'assembly', 'statistics', 'media', 'other')),
  self_evidence  TEXT CHECK (self_evidence IN ('linked_by_official', 'mutual_link')),
  doc_kind       TEXT CHECK (doc_kind IN ('election_bulletin', 'election_notice')),
  published_date DATE,
  fetched_at     TIMESTAMPTZ,
  archive_url    TEXT,
  origin         TEXT NOT NULL CHECK (btrim(origin) <> ''),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT sources_url_http CHECK (url ~* '^https?://'),
  CONSTRAINT sources_archive_url_http CHECK (archive_url IS NULL OR archive_url ~* '^https?://'),
  -- 本人來源一定要有認定根據；有根據就一定是本人來源（防冒名：沒有根據的本人帳號視為 media）
  CONSTRAINT sources_self_needs_evidence CHECK ((source_kind = 'self') = (self_evidence IS NOT NULL))
);
COMMENT ON TABLE policy_jp.sources IS '出處（一個網址一列），任何資料都用 source_refs 引用。正見 public.sources 的日本版（#39）';
COMMENT ON COLUMN policy_jp.sources.source_kind IS
  'official 自治体・選管公文、予算書、施政方針、選挙公報、告示、議会官網議員一覧／self 本人（需 self_evidence）／assembly 議会会議録／'
  'statistics 総務省・e-Stat・議長会調查（數字類）／media 新聞報導與沒有認定根據的社群／other 其他。'
  '正見只有四級：assembly 與 statistics 在正見都歸 official（兩站對照時這樣換算）';
COMMENT ON COLUMN policy_jp.sources.self_evidence IS
  '本人來源的認定根據：linked_by_official 被議會・選管・政黨官網連結／mutual_link 與本人官網互相連結。平台認證（platform_verified）不收：社群貼文不能標 self（同正見協議 1.62.0）';
COMMENT ON COLUMN policy_jp.sources.doc_kind IS 'election_bulletin 選挙公報／election_notice 選管的告示・結果；這兩類要存檔（archive_url），見視圖 source_archive_missing';
COMMENT ON COLUMN policy_jp.sources.fetched_at IS '擷取時間；不知道就留空，不編造（同正見）';
COMMENT ON COLUMN policy_jp.sources.archive_url IS
  '存檔網址。公報・公告類必須有，但改成「可空＋健康檢查」：交件當下先登記，由排程補存檔（SCHEMA v0.7 寫必填，見待定事項 2）。'
  '總務省 robots.txt 擋 Internet Archive，總務省頁面要用國立國會圖書館 WARP 或其他方式';
COMMENT ON COLUMN policy_jp.sources.origin IS '這列最早從哪裡來（contribution＝任務回報落庫、manual＝維護者手動 等）';

CREATE TABLE IF NOT EXISTS policy_jp.source_refs (
  source_id    BIGINT NOT NULL REFERENCES policy_jp.sources(id) ON DELETE CASCADE,
  target_table TEXT NOT NULL CHECK (target_table IN (
                 'elections', 'election_districts', 'politicians', 'politician_careers', 'politician_elections',
                 'politician_election_status', 'candidacy_endorsements', 'politician_offices', 'assembly_factions',
                 'local_governments', 'local_government_successions', 'parties', 'policies', 'policy_elements',
                 'tracking_logs', 'lineages', 'lineage_participants', 'lineage_links', 'handovers', 'reviews')),
  target_id    TEXT NOT NULL,
  role         TEXT NOT NULL DEFAULT 'primary' CHECK (role IN ('primary', 'supporting')),
  origin       TEXT NOT NULL CHECK (btrim(origin) <> ''),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (target_table, target_id, source_id)
);
CREATE INDEX IF NOT EXISTS source_refs_source_idx ON policy_jp.source_refs (source_id);
COMMENT ON TABLE policy_jp.source_refs IS
  '哪一筆資料引用了哪個出處（同正見 public.source_refs）。role：primary＝主要出處／supporting＝一併附上的其他來源。'
  'target_table＝politician_election_status：參選「目前狀態」的出處（SCHEMA 的 status_source_ids；沒有就不顯示那筆參選）；'
  'target_table＝reviews：查核紀錄依據的出處（SCHEMA 的 evidence_source_ids）。指向不存在的資料列看視圖 source_refs_orphans';

-- ------------------------------------------------------------
-- 2. 地方公共団体
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.local_governments (
  lg_code              TEXT PRIMARY KEY CHECK (policy_jp.lg_code_valid(lg_code)),
  kind                 TEXT NOT NULL CHECK (kind IN ('prefecture', 'designated_city', 'core_city', 'city', 'special_ward',
                                                     'admin_ward', 'town', 'village')),
  pref_code            TEXT NOT NULL REFERENCES policy_jp.local_governments(lg_code),
  name                 TEXT NOT NULL CHECK (btrim(name) <> ''),
  kana                 TEXT NOT NULL CHECK (btrim(kana) <> ''),
  slug                 TEXT NOT NULL UNIQUE,
  assembly_seats       INTEGER CHECK (assembly_seats IS NULL OR assembly_seats > 0),
  assembly_seats_as_of DATE,
  valid_from           DATE,
  valid_to             DATE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT local_governments_pref_self CHECK ((kind = 'prefecture') = (pref_code = lg_code)),
  CONSTRAINT local_governments_seats_as_of CHECK ((assembly_seats IS NULL) = (assembly_seats_as_of IS NULL)),
  CONSTRAINT local_governments_admin_ward_no_assembly CHECK (kind <> 'admin_ward' OR assembly_seats IS NULL),
  CONSTRAINT local_governments_valid_period CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from)
);
CREATE INDEX IF NOT EXISTS local_governments_pref_idx ON policy_jp.local_governments (pref_code) WHERE valid_to IS NULL;
COMMENT ON TABLE policy_jp.local_governments IS
  '地方公共団体（主鍵＝總務省全国地方公共団体コード 6 碼含檢查碼）。admin_ward＝政令市的行政区（沒有選舉、沒有議會）。'
  '北方領土 6 村（016951〜017001）代碼表有但沒有議會，建議不收（docs/handoff 說明）';
COMMENT ON COLUMN policy_jp.local_governments.assembly_seats IS '議會的現行定數（#12 對帳的分母）；出處用 source_refs（target_table=local_governments）';

CREATE TABLE IF NOT EXISTS policy_jp.local_government_successions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_lg_code TEXT NOT NULL REFERENCES policy_jp.local_governments(lg_code),
  to_lg_code   TEXT NOT NULL REFERENCES policy_jp.local_governments(lg_code),
  date         DATE NOT NULL,
  kind         TEXT NOT NULL CHECK (kind IN ('merge', 'absorb', 'split', 'rename')),
  note         TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT local_government_successions_distinct CHECK (from_lg_code <> to_lg_code OR kind = 'rename'),
  CONSTRAINT local_government_successions_unique UNIQUE (from_lg_code, to_lg_code, date)
);
COMMENT ON TABLE policy_jp.local_government_successions IS '合併・編入・分割・改名（總務省「改正一覧表」）。歷代首長與政策系譜跨合併接起來用';

-- ------------------------------------------------------------
-- 3. 政黨、人物、學經歷
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.parties (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL CHECK (btrim(name) <> ''),
  kana           TEXT NOT NULL CHECK (btrim(kana) <> ''),
  short_name     TEXT,
  predecessor_id TEXT REFERENCES policy_jp.parties(id),
  valid_from     DATE,
  valid_to       DATE,
  note           TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT parties_valid_period CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from),
  CONSTRAINT parties_not_own_predecessor CHECK (predecessor_id IS NULL OR predecessor_id <> id)
);
COMMENT ON TABLE policy_jp.parties IS '政黨。改名視為新的一列（predecessor_id 指前身）。「無所属」不是一列：politician_elections.party_id 為空＋party_basis 有值＝無所属';

CREATE TABLE IF NOT EXISTS policy_jp.politicians (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL CHECK (btrim(name) <> ''),
  kana          TEXT NOT NULL CHECK (btrim(kana) <> ''),
  birth_year    INTEGER CHECK (birth_year IS NULL OR birth_year BETWEEN 1900 AND 2100),
  review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS politicians_kana_birth_idx ON policy_jp.politicians (kana, birth_year);
COMMENT ON TABLE policy_jp.politicians IS '人物。不存職稱、地區、簡介。同一人＝kana＋地區（任期或參選的 lg_code）＋birth_year 三者相同；不能只用漢字姓名';

CREATE TABLE IF NOT EXISTS policy_jp.politician_careers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  politician_id TEXT NOT NULL REFERENCES policy_jp.politicians(id) ON DELETE CASCADE,
  kind          TEXT NOT NULL CHECK (kind IN ('education', 'career')),
  text          TEXT NOT NULL CHECK (btrim(text) <> ''),
  start_year    INTEGER CHECK (start_year IS NULL OR start_year BETWEEN 1900 AND 2100),
  end_year      INTEGER CHECK (end_year IS NULL OR end_year BETWEEN 1900 AND 2100),
  sort_order    INTEGER NOT NULL DEFAULT 0,
  review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT politician_careers_years CHECK (start_year IS NULL OR end_year IS NULL OR end_year >= start_year),
  CONSTRAINT politician_careers_unique UNIQUE (politician_id, kind, text)
);
COMMENT ON TABLE policy_jp.politician_careers IS '學經歷（同一人同一種同一段文字只一列）。每筆都要有出處（source_refs）；沒有出處的要不要收是待定事項 6';

-- ------------------------------------------------------------
-- 4. 政策系譜（議題）——elections.lineage_id 會指到這裡，所以先建
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.lineages (
  id            TEXT PRIMARY KEY,
  title         TEXT NOT NULL CHECK (btrim(title) <> ''),
  category      TEXT,
  level         TEXT NOT NULL CHECK (level IN ('national', 'regional', 'local')),
  lg_code       TEXT REFERENCES policy_jp.local_governments(lg_code),
  summary       TEXT,
  review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- 國政沒有地方；都道府県・市区町村要有団体（同正見 lineages_place 的意思）
  CONSTRAINT lineages_place CHECK ((level = 'national') = (lg_code IS NULL))
);
COMMENT ON TABLE policy_jp.lineages IS '政策系譜（議題）。level：national 國政／regional 都道府県／local 市区町村（正見是 national／county／township）';

-- ------------------------------------------------------------
-- 5. 選舉
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.elections (
  id              TEXT PRIMARY KEY CHECK (id ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}_[a-z_]+_([0-9]{6}|national)$'),
  name            TEXT NOT NULL CHECK (btrim(name) <> ''),
  election_date   DATE NOT NULL,
  notice_date     DATE,
  election_type   TEXT NOT NULL CHECK (election_type IN ('governor', 'mayor', 'ward_mayor', 'town_mayor', 'national_lower',
                                                         'national_upper', 'pref_assembly', 'muni_assembly')),
  election_reason TEXT NOT NULL CHECK (election_reason IN ('regular', 'resignation', 'death', 'recall', 'dissolution',
                                                           'by_election', 'increase', 'rerun')),
  level           TEXT NOT NULL CHECK (level IN ('national', 'regional', 'local')),
  jurisdiction    TEXT NOT NULL DEFAULT 'jp' CHECK (jurisdiction = 'jp'),
  timezone        TEXT NOT NULL DEFAULT 'Asia/Tokyo' CHECK (timezone = 'Asia/Tokyo'),
  lg_code         TEXT REFERENCES policy_jp.local_governments(lg_code),
  seats           INTEGER CHECK (seats IS NULL OR seats > 0),
  turnout         NUMERIC(5, 2) CHECK (turnout IS NULL OR turnout BETWEEN 0 AND 100),
  lineage_id      TEXT REFERENCES policy_jp.lineages(id),
  note            TEXT,
  review_status   TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT elections_level_matches_type CHECK (level = policy_jp.election_level(election_type)),
  CONSTRAINT elections_national_no_lg CHECK ((level = 'national') = (lg_code IS NULL)),
  CONSTRAINT elections_notice_before_polling CHECK (notice_date IS NULL OR notice_date <= election_date),
  -- 補欠・増員は議員選挙だけ
  CONSTRAINT elections_by_election_assembly CHECK (
    election_reason NOT IN ('by_election', 'increase')
    OR election_type IN ('pref_assembly', 'muni_assembly', 'national_lower', 'national_upper'))
);
CREATE INDEX IF NOT EXISTS elections_date_type_idx ON policy_jp.elections (election_date DESC, election_type);
CREATE INDEX IF NOT EXISTS elections_lg_date_idx ON policy_jp.elections (lg_code, election_date DESC);
COMMENT ON TABLE policy_jp.elections IS
  '選舉。id＝正見的 election_key：日期＋種類＋地區（2027-04-11_governor_130001；國政 2024-10-27_national_lower_national），'
  '同日同地區同種類只有一場，建立後不改（日期或種類填錯只改欄位）。scope_code（正見 PLAN 第 6 節）＝lg_code。'
  '候選人數不存，要時從 politician_elections 算。無投票当選記在 election_districts.is_uncontested';
COMMENT ON COLUMN policy_jp.elections.election_reason IS
  'regular 任期満了／resignation 辞職／death 死亡／recall 解職請求（リコール）成立後に行われる選挙——台灣的 recall 是罷免投票本身，日本這裡是解職後補選首長・議員的那場選舉／'
  'dissolution 不信任・出直し・解散／by_election 補欠選挙／increase 増員選挙／rerun 再選挙（當選無效、當選人不足等）';
COMMENT ON COLUMN policy_jp.elections.level IS '正見 PLAN 第 6 節：national 國政／regional 都道府県／local 市区町村，由 election_type 決定（CHECK）';
COMMENT ON COLUMN policy_jp.elections.turnout IS '投票率（%）。不是得票數也不是得票率；投票前為空';

CREATE TABLE IF NOT EXISTS policy_jp.election_districts (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  election_id       TEXT NOT NULL REFERENCES policy_jp.elections(id) ON DELETE CASCADE,
  district_kind     TEXT NOT NULL CHECK (district_kind IN ('district', 'proportional', 'at_large')),
  district_name     TEXT,
  district_lg_code  TEXT REFERENCES policy_jp.local_governments(lg_code),
  district_lg_codes TEXT[] NOT NULL DEFAULT '{}',
  seats             INTEGER CHECK (seats IS NULL OR seats > 0),
  seats_basis       TEXT CHECK (seats_basis IN ('law', 'notice')),
  is_uncontested    BOOLEAN,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT election_districts_unique UNIQUE NULLS NOT DISTINCT (election_id, district_kind, district_name),
  CONSTRAINT election_districts_name CHECK ((district_kind = 'at_large') = (district_name IS NULL)),
  CONSTRAINT election_districts_merged CHECK (cardinality(district_lg_codes) = 0 OR (district_lg_code IS NULL AND cardinality(district_lg_codes) >= 2)),
  CONSTRAINT election_districts_seats_basis CHECK ((seats IS NULL) = (seats_basis IS NULL))
);
COMMENT ON TABLE policy_jp.election_districts IS '選挙区と定数。各選挙区 seats 的合計不超過 elections.seats；有選挙区列的選舉，參選人的 district_kind＋district_name 要對得上其中一列';
COMMENT ON COLUMN policy_jp.election_districts.seats_basis IS 'law＝法律・條例定死（首長 1 人、議員定數條例）／notice＝選管告示';
COMMENT ON COLUMN policy_jp.election_districts.is_uncontested IS '無投票当選（候選人數不超過定數，不投票）。依選管告示填，不要用「候選人數 ≤ 定數」推（資料沒收齊會誤判）；空＝還不知道';
COMMENT ON COLUMN policy_jp.election_districts.district_lg_codes IS '合区（参院の鳥取・島根、徳島・高知）才填兩縣代碼，此時 district_lg_code 為空；其他為空陣列';

-- ------------------------------------------------------------
-- 6. 參選、推薦、會派、任期
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.politician_elections (
  id                     TEXT PRIMARY KEY,
  politician_id          TEXT NOT NULL REFERENCES policy_jp.politicians(id) ON DELETE CASCADE,
  election_id            TEXT NOT NULL REFERENCES policy_jp.elections(id),
  party_id               TEXT REFERENCES policy_jp.parties(id),
  party_basis            TEXT CHECK (party_basis IN ('contribution', 'official_list')),
  candidacy_status       TEXT NOT NULL CHECK (candidacy_status IN ('considering', 'declared', 'filed', 'withdrawn', 'elected', 'not_elected')),
  withdrawn_after_filing BOOLEAN,
  status_date            DATE NOT NULL,
  district_kind          TEXT NOT NULL CHECK (district_kind IN ('district', 'proportional', 'at_large')),
  district_name          TEXT,
  district_lg_code       TEXT REFERENCES policy_jp.local_governments(lg_code),
  district_lg_codes      TEXT[] NOT NULL DEFAULT '{}',
  list_rank              INTEGER CHECK (list_rank IS NULL OR list_rank > 0),
  is_priority_list       BOOLEAN NOT NULL DEFAULT false,
  note                   TEXT,
  review_status          TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT politician_elections_unique UNIQUE (politician_id, election_id),
  CONSTRAINT politician_elections_party_needs_basis CHECK (party_id IS NULL OR party_basis IS NOT NULL),
  CONSTRAINT politician_elections_withdrawn_flag CHECK (withdrawn_after_filing IS NULL OR candidacy_status = 'withdrawn'),
  CONSTRAINT politician_elections_district_name CHECK ((district_kind = 'at_large') = (district_name IS NULL)),
  CONSTRAINT politician_elections_merged CHECK (cardinality(district_lg_codes) = 0 OR (district_lg_code IS NULL AND cardinality(district_lg_codes) >= 2)),
  CONSTRAINT politician_elections_list_rank_proportional CHECK (list_rank IS NULL OR district_kind = 'proportional'),
  CONSTRAINT politician_elections_priority_proportional CHECK (NOT is_priority_list OR district_kind = 'proportional')
);
CREATE INDEX IF NOT EXISTS politician_elections_election_idx ON policy_jp.politician_elections (election_id);
CREATE INDEX IF NOT EXISTS politician_elections_politician_idx ON policy_jp.politician_elections (politician_id);
COMMENT ON TABLE policy_jp.politician_elections IS
  '參選。不存得票數、得票率，不排名次。每個參選人（不論狀態）都有人物頁。目前狀態的出處用 source_refs（target_table=politician_election_status），沒有出處就不顯示這筆';
COMMENT ON COLUMN policy_jp.politician_elections.candidacy_status IS
  'considering 出馬を検討（本人或政黨公開表態）／declared 立候補を表明／filed 立候補届出（告示日後）／withdrawn 取りやめ・辞退／elected 当選／not_elected 落選。不收傳聞';
COMMENT ON COLUMN policy_jp.politician_elections.withdrawn_after_filing IS
  'withdrawn 才有值：true＝届出後に辞退（告示後に立候補を取り下げ）／false＝届出前に出馬取りやめ／空＝不是退選或還不知道（同正見）';
COMMENT ON COLUMN policy_jp.politician_elections.party_id IS '本人那一次參選時所屬的政黨。推薦・支持另列於 candidacy_endorsements';
COMMENT ON COLUMN policy_jp.politician_elections.party_basis IS
  'party_id 的根據：contribution＝交件寫的／official_list＝選管的候補者名單。party_basis 有值而 party_id 空＝無所属；party_basis 空＝還不知道（同正見的分法）';
COMMENT ON COLUMN policy_jp.politician_elections.list_rank IS '比例代表的名簿順位（排序依據，不是票數，可以顯示）';

CREATE TABLE IF NOT EXISTS policy_jp.candidacy_endorsements (
  id                     TEXT PRIMARY KEY,
  politician_election_id TEXT NOT NULL REFERENCES policy_jp.politician_elections(id) ON DELETE CASCADE,
  party_id               TEXT NOT NULL REFERENCES policy_jp.parties(id),
  kind                   TEXT NOT NULL CHECK (kind IN ('nominated', 'recommended', 'supported')),
  announced_on           DATE NOT NULL,
  review_status          TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT candidacy_endorsements_unique UNIQUE (politician_election_id, party_id, kind)
);
COMMENT ON TABLE policy_jp.candidacy_endorsements IS '政黨的公認・推薦・支持（出處必填，用 source_refs）。不做勝率、席次排行或評分';

CREATE TABLE IF NOT EXISTS policy_jp.assembly_factions (
  id         TEXT PRIMARY KEY,
  lg_code    TEXT NOT NULL REFERENCES policy_jp.local_governments(lg_code),
  name       TEXT NOT NULL CHECK (btrim(name) <> ''),
  valid_from DATE,
  valid_to   DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT assembly_factions_valid_period CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from)
);
COMMENT ON TABLE policy_jp.assembly_factions IS '議會会派（會派≠政黨，跟 party_id 分開存）。会派常改名、分裂；現存者 valid_to 為空';

CREATE TABLE IF NOT EXISTS policy_jp.politician_offices (
  id                     TEXT PRIMARY KEY,
  politician_id          TEXT NOT NULL REFERENCES policy_jp.politicians(id) ON DELETE CASCADE,
  position               TEXT NOT NULL CHECK (position IN ('governor', 'mayor', 'ward_mayor', 'town_mayor', 'pref_assembly_member',
                                                           'muni_assembly_member', 'representative', 'councillor')),
  lg_code                TEXT REFERENCES policy_jp.local_governments(lg_code),
  term_no                INTEGER NOT NULL CHECK (term_no > 0),
  start_date             DATE NOT NULL,
  scheduled_end_date     DATE NOT NULL,
  end_date               DATE,
  end_reason             TEXT CHECK (end_reason IN ('term_expired', 'took_other_office', 'resigned', 'recalled', 'deceased', 'removed', 'other')),
  end_basis              TEXT CHECK (end_basis IN ('law', 'inferred', 'source')),
  election_id            TEXT REFERENCES policy_jp.elections(id),
  politician_election_id TEXT REFERENCES policy_jp.politician_elections(id) ON DELETE SET NULL,
  faction_id             TEXT REFERENCES policy_jp.assembly_factions(id),
  review_status          TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT politician_offices_term_order CHECK (scheduled_end_date >= start_date),
  CONSTRAINT politician_offices_end_order CHECK (end_date IS NULL OR end_date >= start_date - 1),
  -- 有卸任日就要有卸任原因與判定依據；在任中三欄都是空的（同正見）
  CONSTRAINT politician_offices_end_fields CHECK ((end_date IS NULL) = (end_reason IS NULL) AND (end_date IS NULL) = (end_basis IS NULL)),
  -- 國會議員（representative／councillor）才可以不掛団体
  CONSTRAINT politician_offices_lg_needed CHECK (lg_code IS NOT NULL OR position IN ('representative', 'councillor')),
  CONSTRAINT politician_offices_faction_only_members CHECK (faction_id IS NULL OR position IN ('pref_assembly_member', 'muni_assembly_member'))
);
CREATE INDEX IF NOT EXISTS politician_offices_current_idx ON policy_jp.politician_offices (lg_code, end_date) WHERE end_date IS NULL;
CREATE INDEX IF NOT EXISTS politician_offices_position_idx ON policy_jp.politician_offices (position, lg_code);
CREATE INDEX IF NOT EXISTS politician_offices_schedule_idx ON policy_jp.politician_offices (scheduled_end_date) WHERE end_date IS NULL;
COMMENT ON TABLE policy_jp.politician_offices IS '任期。現任＝end_date 為空（只有這一種判法）。首長的 term_no＝同一人同職位第幾期；議員＝同 position＋同 lg_code 的當選回數';
COMMENT ON COLUMN policy_jp.politician_offices.end_reason IS 'term_expired 任期満了／took_other_office 轉任／resigned 辞職／recalled 解職（リコール）／deceased 死亡／removed 失職・除名等／other';
COMMENT ON COLUMN policy_jp.politician_offices.end_basis IS 'law＝依法推得（任期満了日）／inferred＝從其他資料推得（例：後任就任）／source＝有出處明寫';
COMMENT ON COLUMN policy_jp.politician_offices.politician_election_id IS '產生這個任期的那筆參選（無投票当選也有）';

-- ------------------------------------------------------------
-- 7. 政策、三要素、追蹤
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.policies (
  id                     TEXT PRIMARY KEY,
  title                  TEXT NOT NULL CHECK (btrim(title) <> ''),
  description            TEXT NOT NULL CHECK (char_length(description) BETWEEN 1 AND 120),
  category               TEXT NOT NULL,
  origin                 TEXT NOT NULL CHECK (origin IN ('pledge', 'policy_address', 'assembly', 'budget')),
  source_locator         TEXT,
  politician_election_id TEXT REFERENCES policy_jp.politician_elections(id),
  lg_code                TEXT REFERENCES policy_jp.local_governments(lg_code),
  office_ids             TEXT[] NOT NULL DEFAULT '{}',
  lineage_id             TEXT REFERENCES policy_jp.lineages(id),
  status                 TEXT NOT NULL CHECK (status IN ('not_started', 'in_progress', 'partial', 'achieved', 'discontinued', 'unfulfilled')),
  proposed_date          DATE,
  last_updated           DATE,
  review_status          TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT policies_pledge_needs_candidacy CHECK ((origin = 'pledge') = (politician_election_id IS NOT NULL)),
  CONSTRAINT policies_locator_needed CHECK (origin NOT IN ('pledge', 'assembly') OR (source_locator IS NOT NULL AND btrim(source_locator) <> '')),
  CONSTRAINT policies_unfulfilled_only_pledge CHECK (status <> 'unfulfilled' OR origin = 'pledge')
);
CREATE INDEX IF NOT EXISTS policies_lg_idx ON policy_jp.policies (lg_code);
CREATE INDEX IF NOT EXISTS policies_candidacy_idx ON policy_jp.policies (politician_election_id) WHERE politician_election_id IS NOT NULL;
COMMENT ON TABLE policy_jp.policies IS
  '政策。description 是要約：120 字以內、只寫事實。pledge（公約）掛在參選上；落選者的公約只出現在選舉專區與人物頁。'
  'office_ids 是任期 id 的陣列（跨多任期；資料庫不檢查外鍵，跟 SCHEMA 一樣）。discontinued 至少要一個 official 或 assembly 出處（寫入端檢查）';

CREATE TABLE IF NOT EXISTS policy_jp.policy_elements (
  id             TEXT PRIMARY KEY,
  policy_id      TEXT NOT NULL REFERENCES policy_jp.policies(id) ON DELETE CASCADE,
  element        TEXT NOT NULL CHECK (element IN ('target', 'deadline', 'funding')),
  stated         BOOLEAN NOT NULL,
  text           TEXT CHECK (text IS NULL OR char_length(text) BETWEEN 1 AND 120),
  deadline_date  DATE,
  source_locator TEXT,
  review_status  TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT policy_elements_unique UNIQUE (policy_id, element),
  CONSTRAINT policy_elements_stated_text CHECK (stated = (text IS NOT NULL)),
  CONSTRAINT policy_elements_deadline_date CHECK (deadline_date IS NULL OR (element = 'deadline' AND stated))
);
COMMENT ON TABLE policy_jp.policy_elements IS
  '政見三要素（數值目標・達成期限・財源），一個要素一列。沒有列＝還沒拆（未調査）；stated=false＝查過原文沒寫（未説明），也要附出處（查的是哪份原文）';

CREATE TABLE IF NOT EXISTS policy_jp.tracking_logs (
  id            TEXT PRIMARY KEY,
  policy_id     TEXT NOT NULL REFERENCES policy_jp.policies(id) ON DELETE CASCADE,
  date          DATE NOT NULL,
  event         TEXT NOT NULL CHECK (btrim(event) <> ''),
  description   TEXT,
  review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tracking_logs_policy_idx ON policy_jp.tracking_logs (policy_id, date);

-- ------------------------------------------------------------
-- 8. 系譜的參與者、上下關係、交接
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.lineage_participants (
  id             TEXT PRIMARY KEY,
  lineage_id     TEXT NOT NULL REFERENCES policy_jp.lineages(id) ON DELETE CASCADE,
  politician_id  TEXT NOT NULL REFERENCES policy_jp.politicians(id),
  role           TEXT NOT NULL CHECK (role IN ('proposer', 'co_proposer', 'cosigner', 'advocate')),
  basis          TEXT NOT NULL CHECK (basis IN ('official_record', 'self_claim')),
  source_locator TEXT NOT NULL CHECK (char_length(btrim(source_locator)) BETWEEN 1 AND 200),
  note           TEXT CHECK (note IS NULL OR char_length(btrim(note)) BETWEEN 1 AND 200),
  review_status  TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT lineage_participants_one_per_basis UNIQUE (lineage_id, politician_id, basis)
);
COMMENT ON TABLE policy_jp.lineage_participants IS
  '系譜的參與者（同正見 #378）：官方紀錄一個角色、本人宣稱一個角色，兩者並列。正見的 source_url 欄改用 source_refs（target_table=lineage_participants）';

CREATE TABLE IF NOT EXISTS policy_jp.lineage_links (
  id               TEXT PRIMARY KEY,
  upper_lineage_id TEXT NOT NULL REFERENCES policy_jp.lineages(id) ON DELETE CASCADE,
  lower_lineage_id TEXT NOT NULL REFERENCES policy_jp.lineages(id) ON DELETE CASCADE,
  link_type        TEXT NOT NULL CHECK (link_type IN ('top_down', 'bottom_up')),
  note             TEXT NOT NULL CHECK (char_length(btrim(note)) BETWEEN 20 AND 500),
  source_locator   TEXT NOT NULL CHECK (char_length(btrim(source_locator)) BETWEEN 1 AND 200),
  review_status    TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT lineage_links_not_self CHECK (upper_lineage_id <> lower_lineage_id),
  CONSTRAINT lineage_links_one_per_pair UNIQUE (upper_lineage_id, lower_lineage_id)
);
COMMENT ON TABLE policy_jp.lineage_links IS '上下層系譜的關係（同正見 #378）：top_down 國→都道府県→市区町村的政策落到地方／bottom_up 地方先做、上層跟進';

CREATE TABLE IF NOT EXISTS policy_jp.handovers (
  id              TEXT PRIMARY KEY,
  lineage_id      TEXT NOT NULL REFERENCES policy_jp.lineages(id) ON DELETE CASCADE,
  from_office_id  TEXT NOT NULL REFERENCES policy_jp.politician_offices(id),
  to_office_id    TEXT NOT NULL REFERENCES policy_jp.politician_offices(id),
  from_policy_ids TEXT[] NOT NULL DEFAULT '{}',
  to_policy_ids   TEXT[] NOT NULL DEFAULT '{}',
  handover_type   TEXT NOT NULL CHECK (handover_type IN ('keep', 'pivot', 'shrink', 'stop', 'resume')),
  decided_on      DATE,
  note            TEXT,
  source_locator  TEXT,
  review_status   TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT handovers_distinct_terms CHECK (from_office_id <> to_office_id),
  CONSTRAINT handovers_one_per_pair UNIQUE (lineage_id, from_office_id, to_office_id)
);
COMMENT ON TABLE policy_jp.handovers IS
  '交接：換任時這條政策怎麼被處理（與正見 #331 同值）。stop（廃止）至少要一個 official 或 assembly 出處（寫入端檢查）。source_locator：讓查核的人回到原句';

-- ------------------------------------------------------------
-- 9. 查核紀錄
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_jp.reviews (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_table  TEXT NOT NULL CHECK (target_table IN (
                  'elections', 'election_districts', 'politicians', 'politician_careers', 'politician_elections',
                  'candidacy_endorsements', 'politician_offices', 'policies', 'policy_elements', 'tracking_logs',
                  'lineages', 'lineage_participants', 'lineage_links', 'handovers')),
  target_id     TEXT NOT NULL,
  review_status TEXT NOT NULL CHECK (review_status IN ('pending', 'published', 'rejected', 'not_found')),
  reviewer_kind TEXT NOT NULL CHECK (reviewer_kind IN ('human', 'agent')),
  reviewer      TEXT NOT NULL CHECK (btrim(reviewer) <> ''),
  reviewed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  checked_urls  TEXT[] NOT NULL DEFAULT '{}',
  note          TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT reviews_not_found_needs_urls CHECK (review_status <> 'not_found' OR cardinality(checked_urls) > 0)
);
CREATE INDEX IF NOT EXISTS reviews_target_idx ON policy_jp.reviews (target_table, target_id, reviewed_at);
COMMENT ON TABLE policy_jp.reviews IS
  '查核紀錄（一筆資料可以有多筆）。各表的 review_status 是快取，值等於最新一筆 reviews；不一致以 reviews 為準。'
  'reviewer：人＝顯示名稱，代理＝精確的模型 ID。依據的出處用 source_refs（target_table=reviews）';

-- ------------------------------------------------------------
-- 10. updated_at 觸發器
-- ------------------------------------------------------------
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['local_governments', 'parties', 'politicians', 'politician_careers', 'lineages', 'elections',
                           'election_districts', 'politician_elections', 'candidacy_endorsements', 'assembly_factions',
                           'politician_offices', 'policies', 'policy_elements', 'tracking_logs', 'lineage_participants',
                           'lineage_links', 'handovers'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%1$s_touch ON policy_jp.%1$I', t);
    EXECUTE format('CREATE TRIGGER trg_%1$s_touch BEFORE UPDATE ON policy_jp.%1$I FOR EACH ROW EXECUTE FUNCTION policy_jp.touch_updated_at()', t);
  END LOOP;
END
$$;

-- ------------------------------------------------------------
-- 11. 健康檢查視圖（正常是空的）
-- ------------------------------------------------------------
-- 出處引用指到不存在的資料列（source_refs 是多型關聯，沒辦法用外鍵擋）
CREATE OR REPLACE VIEW policy_jp.source_refs_orphans WITH (security_invoker = true) AS
  SELECT r.* FROM policy_jp.source_refs r
   WHERE NOT CASE r.target_table
     WHEN 'elections'                    THEN EXISTS (SELECT 1 FROM policy_jp.elections x WHERE x.id = r.target_id)
     WHEN 'election_districts'           THEN EXISTS (SELECT 1 FROM policy_jp.election_districts x WHERE x.id::TEXT = r.target_id)
     WHEN 'politicians'                  THEN EXISTS (SELECT 1 FROM policy_jp.politicians x WHERE x.id = r.target_id)
     WHEN 'politician_careers'           THEN EXISTS (SELECT 1 FROM policy_jp.politician_careers x WHERE x.id::TEXT = r.target_id)
     WHEN 'politician_elections'         THEN EXISTS (SELECT 1 FROM policy_jp.politician_elections x WHERE x.id = r.target_id)
     WHEN 'politician_election_status'   THEN EXISTS (SELECT 1 FROM policy_jp.politician_elections x WHERE x.id = r.target_id)
     WHEN 'candidacy_endorsements'       THEN EXISTS (SELECT 1 FROM policy_jp.candidacy_endorsements x WHERE x.id = r.target_id)
     WHEN 'politician_offices'           THEN EXISTS (SELECT 1 FROM policy_jp.politician_offices x WHERE x.id = r.target_id)
     WHEN 'assembly_factions'            THEN EXISTS (SELECT 1 FROM policy_jp.assembly_factions x WHERE x.id = r.target_id)
     WHEN 'local_governments'            THEN EXISTS (SELECT 1 FROM policy_jp.local_governments x WHERE x.lg_code = r.target_id)
     WHEN 'local_government_successions' THEN EXISTS (SELECT 1 FROM policy_jp.local_government_successions x WHERE x.id::TEXT = r.target_id)
     WHEN 'parties'                      THEN EXISTS (SELECT 1 FROM policy_jp.parties x WHERE x.id = r.target_id)
     WHEN 'policies'                     THEN EXISTS (SELECT 1 FROM policy_jp.policies x WHERE x.id = r.target_id)
     WHEN 'policy_elements'              THEN EXISTS (SELECT 1 FROM policy_jp.policy_elements x WHERE x.id = r.target_id)
     WHEN 'tracking_logs'                THEN EXISTS (SELECT 1 FROM policy_jp.tracking_logs x WHERE x.id = r.target_id)
     WHEN 'lineages'                     THEN EXISTS (SELECT 1 FROM policy_jp.lineages x WHERE x.id = r.target_id)
     WHEN 'lineage_participants'         THEN EXISTS (SELECT 1 FROM policy_jp.lineage_participants x WHERE x.id = r.target_id)
     WHEN 'lineage_links'                THEN EXISTS (SELECT 1 FROM policy_jp.lineage_links x WHERE x.id = r.target_id)
     WHEN 'handovers'                    THEN EXISTS (SELECT 1 FROM policy_jp.handovers x WHERE x.id = r.target_id)
     WHEN 'reviews'                      THEN EXISTS (SELECT 1 FROM policy_jp.reviews x WHERE x.id::TEXT = r.target_id)
     ELSE false
   END;
COMMENT ON VIEW policy_jp.source_refs_orphans IS '指向不存在資料列的出處引用（正常是空的）。service_role 用，不開放 anon';

-- 公報・公告類還沒存檔的出處（archive_url 改成可空之後，靠這個視圖與之後的排程補上）
CREATE OR REPLACE VIEW policy_jp.source_archive_missing WITH (security_invoker = true) AS
  SELECT s.id, s.url, s.doc_kind, s.created_at FROM policy_jp.sources s
   WHERE s.doc_kind IS NOT NULL AND s.archive_url IS NULL;
COMMENT ON VIEW policy_jp.source_archive_missing IS '選挙公報・選管公告類還沒有 archive_url 的出處（正常是空的；排程存檔補上）。service_role 用';

-- ------------------------------------------------------------
-- 12. 權限：每張表 RLS＋逐表 GRANT（公開資料只給讀）
-- ------------------------------------------------------------
DO $$
DECLARE t TEXT;
BEGIN
  -- 有 review_status 的表：公開讀只看得到 published
  FOREACH t IN ARRAY ARRAY['politicians', 'politician_careers', 'lineages', 'elections', 'politician_elections',
                           'candidacy_endorsements', 'politician_offices', 'policies', 'policy_elements', 'tracking_logs',
                           'lineage_participants', 'lineage_links', 'handovers'] LOOP
    EXECUTE format('ALTER TABLE policy_jp.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS "Public read published" ON policy_jp.%I', t);
    EXECUTE format('CREATE POLICY "Public read published" ON policy_jp.%I FOR SELECT TO anon, authenticated USING (review_status = ''published'')', t);
    EXECUTE format('GRANT SELECT ON policy_jp.%I TO anon, authenticated', t);
  END LOOP;
  -- 參照用的表與出處、查核紀錄：公開讀全部
  FOREACH t IN ARRAY ARRAY['sources', 'source_refs', 'local_governments', 'local_government_successions', 'parties',
                           'assembly_factions', 'election_districts', 'reviews'] LOOP
    EXECUTE format('ALTER TABLE policy_jp.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS "Public read" ON policy_jp.%I', t);
    EXECUTE format('CREATE POLICY "Public read" ON policy_jp.%I FOR SELECT TO anon, authenticated USING (true)', t);
    EXECUTE format('GRANT SELECT ON policy_jp.%I TO anon, authenticated', t);
  END LOOP;
END
$$;
-- 健康檢查視圖不開放給 anon／authenticated（#479 的預設權限只給 service_role）
REVOKE ALL ON policy_jp.source_refs_orphans, policy_jp.source_archive_missing FROM anon, authenticated;

-- ------------------------------------------------------------
-- 13. 自我檢查：做錯就讓這支 migration 失敗
-- ------------------------------------------------------------
DO $$
DECLARE bad TEXT;
BEGIN
  -- (a) 每張表都開 RLS
  SELECT string_agg(c.relname, ', ') INTO bad
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'policy_jp' AND c.relkind = 'r' AND NOT c.relrowsecurity;
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'policy_jp：這些表沒開 RLS：%', bad; END IF;

  -- (b) anon／authenticated 沒有任何寫入權限
  SELECT string_agg(DISTINCT g.table_name || ':' || g.grantee || ':' || g.privilege_type, ', ') INTO bad
    FROM information_schema.role_table_grants g
   WHERE g.table_schema = 'policy_jp' AND g.grantee IN ('anon', 'authenticated', 'PUBLIC')
     AND g.privilege_type IN ('INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'REFERENCES', 'TRIGGER');
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'policy_jp：anon／authenticated 不該有寫入權限：%', bad; END IF;

  -- (c) 日本站不存得票數、得票率（投票率 turnout 不算）
  SELECT string_agg(c.table_name || '.' || c.column_name, ', ') INTO bad
    FROM information_schema.columns c
   WHERE c.table_schema = 'policy_jp' AND c.column_name ~* '(vote|votes|ballot_count|tokuhyo|得票)';
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'policy_jp：日本站不存得票數、得票率：%', bad; END IF;
END
$$;
