-- 學經歷獨立成表 politician_careers，每一項各自帶出處（#346 第一階段，只加不刪）
--
-- 為什麼：人物頁的「學歷」「經歷」讀 politicians.education[]／experience[] 兩個陣列，陣列掛不上出處——
-- 一項學歷是誰查的、看的是哪一頁，資料庫答不出來。日本站（keifu SCHEMA v0.7）從一開始就是
-- politician_careers 一項一列、每項都要出處；正見照它的形狀，出處走 #347 的 sources／source_refs。
--
-- 這支做的事（都是加，沒有刪、沒有改名）：
--   1. 新表 politician_careers：一個人的一項學歷或經歷一列（kind＝education／career，照日本站），
--      文字照陣列原樣、起訖年（start_year／end_year）先空著——陣列只有文字，起訖要等第二階段交件能帶。
--   2. 回填：兩個陣列逐項搬進來（搬移，不是新資料）。2026-10-06 唯讀：學歷 59 人 153 項、經歷 56 人 348 項。
--   3. 出處回填：學經歷是「politician 型別交件、驗證通過、落庫」進來的，那筆交件的 source_urls 就是它的出處；
--      照落庫順序把每筆已落庫交件的網址掛到「文字相同」的項目上（source_refs，target_table＝politician_careers）。
--      其餘（早期整批匯入、舊 AI 管線寫的）沒有出處——不編，標「待補出處」（視圖 politician_careers_full 的 needs_source）。
--      **臉書、IG、Threads 讀不到，不算出處**（#349 同一份清單，supabase/functions/_shared/lineage.ts 的 UNREADABLE_SOCIAL_HOSTS）。
--   4. 同步：陣列欄位保留，任何寫入端照舊寫陣列；陣列一變，觸發器把這個人的學經歷重新對一次
--      （新項目加列、拿掉的項目刪列連同它的出處引用、順序照陣列）。交件落庫（contributions.status 變成 applied）
--      時，politician 型別帶 education／experience 的，觸發器照第 3 點同一條規則把 source_urls 掛上去——
--      **陣列沒變也會掛**：補出處任務的代理是照原文重交同一份學經歷，落庫只補空欄位（fillBlanks），陣列不會動。
--   5. 派工：沒有出處的學經歷，一個人一件「補學經歷條列」任務（沿用 profile_detail_gap 型別，
--      target.kind＝career_sources、task_id＝auto:profile_detail_gap:sources:<人物>），代理找到看得到那幾項的頁面，
--      用 politician 型別照原文重交那幾項＋source_urls；已經有人交了還在等票的先不派。
--   6. 檢查：視圖 politician_careers_drift 列出「陣列有、表沒有」或「表有、陣列沒有」的項目，正常是空的
--      （觸發器出錯只記警告、不擋寫入，跟 #347 出處同步同一個做法，所以要有地方看得到漏了什麼）。
--
-- 沒做的（第二階段）：人物頁改讀這張表、每項附出處或標「待補出處」；交件直接寫這張表（可帶起訖年）、
-- 陣列改成由表衍生，確認兩邊一致後才刪陣列欄位。

-- ------------------------------------------------------------
-- 1. 表
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS politician_careers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  politician_id UUID NOT NULL REFERENCES politicians(id) ON DELETE CASCADE,
  kind          TEXT NOT NULL CHECK (kind IN ('education', 'career')),
  text          TEXT NOT NULL CHECK (btrim(text) <> ''),
  text_key      TEXT NOT NULL,
  start_year    INTEGER CHECK (start_year BETWEEN 1900 AND 2100),
  end_year      INTEGER CHECK (end_year BETWEEN 1900 AND 2100),
  sort_order    INTEGER NOT NULL DEFAULT 0,
  origin        TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT politician_careers_years CHECK (start_year IS NULL OR end_year IS NULL OR end_year >= start_year),
  CONSTRAINT politician_careers_unique UNIQUE (politician_id, kind, text_key)
);
COMMENT ON TABLE politician_careers IS
  '學經歷，一項一列（#346 第一階段）。kind：education 學歷／career 經歷（照日本站）。出處走 sources／source_refs（target_table＝politician_careers）；'
  '沒有出處＝待補出處（看 politician_careers_full.needs_source）。第一階段由 politicians.education[]／experience[] 經觸發器同步，不要直接寫';
COMMENT ON COLUMN politician_careers.text IS '照陣列原文（去頭尾空白）';
COMMENT ON COLUMN politician_careers.text_key IS '比對用的正規化文字（career_text_key：全形轉半形、連續空白收成一個）；同一人同一種只有一列';
COMMENT ON COLUMN politician_careers.start_year IS '起始年（西元）；第一階段陣列沒有這個資訊，一律空著';
COMMENT ON COLUMN politician_careers.end_year IS '結束年（西元）；第一階段一律空著';
COMMENT ON COLUMN politician_careers.sort_order IS '在陣列裡的順序（從 1 起）';
COMMENT ON COLUMN politician_careers.origin IS '這一列怎麼來的：backfill:array（10-06 回填）／array_sync（之後陣列變動同步）';
CREATE INDEX IF NOT EXISTS idx_politician_careers_politician ON politician_careers (politician_id, kind, sort_order);

ALTER TABLE politician_careers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read" ON politician_careers;
CREATE POLICY "Public read" ON politician_careers FOR SELECT USING (true);
DROP POLICY IF EXISTS "Service role write" ON politician_careers;
CREATE POLICY "Service role write" ON politician_careers FOR ALL USING (auth.role() = 'service_role');
GRANT SELECT ON politician_careers TO anon, authenticated;

-- 出處引用可以指到學經歷（target_table 只加不刪；前一版見 20261006034900）
ALTER TABLE source_refs DROP CONSTRAINT IF EXISTS source_refs_target_table_check;
ALTER TABLE source_refs ADD CONSTRAINT source_refs_target_table_check
  CHECK (target_table IN ('policies', 'tracking_logs', 'policy_elements', 'lineage_participants', 'handovers', 'lineage_links', 'politician_careers'));

-- ------------------------------------------------------------
-- 2. 比對規則
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION career_text_key(p_text TEXT) RETURNS TEXT
LANGUAGE sql IMMUTABLE AS $$
  SELECT btrim(regexp_replace(normalize(coalesce(p_text, ''), NFKC), '\s+', ' ', 'g'))
$$;
COMMENT ON FUNCTION career_text_key IS '學經歷比對用的文字：全形轉半形（NFKC）、連續空白收成一個、去頭尾空白。陣列同步與出處掛載都用它（#346）';

-- 讀不到的社群不算出處：臉書、IG、Threads（跟 supabase/functions/_shared/lineage.ts 的 UNREADABLE_SOCIAL_HOSTS 同一份，測試盯兩邊）
CREATE OR REPLACE FUNCTION career_source_readable(p_url TEXT) RETURNS BOOLEAN
LANGUAGE sql IMMUTABLE AS $$
  SELECT coalesce(btrim(p_url), '') ~* '^https?://[^/\s]+'
     AND NOT (lower(substring(btrim(p_url) from '^[A-Za-z]+://([^/:?#]+)'))
              ~ '(^|\.)(facebook\.com|fb\.com|fb\.watch|instagram\.com|threads\.net)$')
$$;
COMMENT ON FUNCTION career_source_readable IS '這個網址能不能當學經歷的出處：要是 http(s) 網址，而且不是臉書、IG、Threads（要登入才看得到，驗證者與系統都打不開）';

-- ------------------------------------------------------------
-- 3. 陣列 → 表（一個人重新對一次）
-- ------------------------------------------------------------
-- 兩個陣列 → 想要的項目（同一個陣列裡重複的只留第一次出現的；空字串不算）
CREATE OR REPLACE FUNCTION politician_career_items(p_education TEXT[], p_experience TEXT[])
RETURNS TABLE (kind TEXT, txt TEXT, key TEXT, ord INTEGER)
LANGUAGE sql IMMUTABLE AS $$
  SELECT DISTINCT ON (s.kind, s.key) s.kind, s.txt, s.key, s.ord
    FROM (
      SELECT 'education' AS kind, btrim(t) AS txt, career_text_key(t) AS key, n::INTEGER AS ord
        FROM unnest(coalesce(p_education, '{}'::TEXT[])) WITH ORDINALITY AS u(t, n)
      UNION ALL
      SELECT 'career', btrim(t), career_text_key(t), n::INTEGER
        FROM unnest(coalesce(p_experience, '{}'::TEXT[])) WITH ORDINALITY AS u(t, n)
    ) s
   WHERE s.key <> ''
   ORDER BY s.kind, s.key, s.ord
$$;

CREATE OR REPLACE FUNCTION politician_careers_sync(p_politician_id UUID, p_origin TEXT DEFAULT 'array_sync') RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_edu TEXT[];
  v_exp TEXT[];
BEGIN
  SELECT education, experience INTO v_edu, v_exp FROM politicians WHERE id = p_politician_id;
  IF NOT FOUND THEN RETURN; END IF;

  -- 陣列裡已經沒有的項目：連同它的出處引用一起拿掉（陣列的變動本身記在 edit_history）
  DELETE FROM source_refs r
   USING politician_careers c
   WHERE c.politician_id = p_politician_id
     AND r.target_table = 'politician_careers' AND r.target_id = c.id::TEXT
     AND NOT EXISTS (SELECT 1 FROM politician_career_items(v_edu, v_exp) w WHERE w.kind = c.kind AND w.key = c.text_key);
  DELETE FROM politician_careers c
   WHERE c.politician_id = p_politician_id
     AND NOT EXISTS (SELECT 1 FROM politician_career_items(v_edu, v_exp) w WHERE w.kind = c.kind AND w.key = c.text_key);

  -- 還在的：順序與原文照陣列
  UPDATE politician_careers c
     SET sort_order = w.ord, text = w.txt, updated_at = now()
    FROM politician_career_items(v_edu, v_exp) w
   WHERE c.politician_id = p_politician_id AND c.kind = w.kind AND c.text_key = w.key
     AND (c.sort_order IS DISTINCT FROM w.ord OR c.text IS DISTINCT FROM w.txt);

  INSERT INTO politician_careers (politician_id, kind, text, text_key, sort_order, origin)
  SELECT p_politician_id, w.kind, w.txt, w.key, w.ord, p_origin
    FROM politician_career_items(v_edu, v_exp) w
   WHERE NOT EXISTS (SELECT 1 FROM politician_careers c
                      WHERE c.politician_id = p_politician_id AND c.kind = w.kind AND c.text_key = w.key);
END;
$$;
REVOKE EXECUTE ON FUNCTION politician_careers_sync(UUID, TEXT) FROM PUBLIC, anon, authenticated;
COMMENT ON FUNCTION politician_careers_sync IS '把一個人的 education[]／experience[] 對到 politician_careers：新項目加列、拿掉的項目刪列（連同出處引用）、順序照陣列（#346）';

-- ------------------------------------------------------------
-- 4. 出處掛載：一筆交件的網址 → 文字相同的學經歷
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION politician_careers_attach_sources(
  p_politician_id UUID, p_education TEXT[], p_experience TEXT[], p_urls TEXT[],
  p_origin TEXT, p_fetched_at TIMESTAMPTZ DEFAULT NULL
) RETURNS INTEGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_urls TEXT[];
  v_count INTEGER := 0;
  v_src BIGINT;
  v_first BOOLEAN;
  r RECORD;
  i INTEGER;
BEGIN
  -- 能讀的網址，照交件的順序、同一個網址只算一次
  SELECT array_agg(u ORDER BY n) INTO v_urls
    FROM (SELECT DISTINCT ON (btrim(x.u)) btrim(x.u) AS u, x.n
            FROM unnest(coalesce(p_urls, '{}'::TEXT[])) WITH ORDINALITY AS x(u, n)
           WHERE career_source_readable(x.u)
           ORDER BY btrim(x.u), x.n) s;
  IF v_urls IS NULL THEN RETURN 0; END IF;

  FOR r IN
    SELECT c.id,
           EXISTS (SELECT 1 FROM source_refs sr
                    WHERE sr.target_table = 'politician_careers' AND sr.target_id = c.id::TEXT AND sr.role = 'primary') AS has_primary
      FROM politician_careers c
     WHERE c.politician_id = p_politician_id
       AND ((c.kind = 'education' AND c.text_key IN (SELECT career_text_key(t) FROM unnest(coalesce(p_education, '{}'::TEXT[])) t))
         OR (c.kind = 'career'    AND c.text_key IN (SELECT career_text_key(t) FROM unnest(coalesce(p_experience, '{}'::TEXT[])) t)))
  LOOP
    v_first := NOT r.has_primary;
    FOR i IN 1 .. array_length(v_urls, 1) LOOP
      v_src := source_upsert(v_urls[i], p_origin, NULL, NULL, NULL, p_fetched_at);
      CONTINUE WHEN v_src IS NULL;
      -- 第一個網址是這一項的主要出處（已經有主要出處的就都記成佐證）
      INSERT INTO source_refs (source_id, target_table, target_id, role, origin)
      VALUES (v_src, 'politician_careers', r.id::TEXT, CASE WHEN v_first THEN 'primary' ELSE 'supporting' END, p_origin)
      ON CONFLICT (target_table, target_id, source_id) DO NOTHING;
      v_first := false;
    END LOOP;
    v_count := v_count + 1;
  END LOOP;
  RETURN v_count;
END;
$$;
REVOKE EXECUTE ON FUNCTION politician_careers_attach_sources(UUID, TEXT[], TEXT[], TEXT[], TEXT, TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
COMMENT ON FUNCTION politician_careers_attach_sources IS
  '把一筆交件的 source_urls 掛到這個人「文字相同」的學經歷上（臉書、IG、Threads 不算）；回傳掛到幾項。回填與落庫觸發器共用（#346）';

-- 交件的學經歷陣列（payload 裡不是陣列就當空的）
CREATE OR REPLACE FUNCTION contribution_career_items(p_payload JSONB, p_key TEXT) RETURNS TEXT[]
LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE WHEN jsonb_typeof(p_payload -> p_key) = 'array'
              THEN ARRAY(SELECT jsonb_array_elements_text(p_payload -> p_key))
              ELSE '{}'::TEXT[] END
$$;

-- ------------------------------------------------------------
-- 5. 回填（搬移）：先表、再出處
-- ------------------------------------------------------------
DO $$
DECLARE
  r RECORD;
  v_people INTEGER := 0;
BEGIN
  FOR r IN SELECT id FROM politicians
            WHERE cardinality(coalesce(education, '{}'::TEXT[])) > 0 OR cardinality(coalesce(experience, '{}'::TEXT[])) > 0
  LOOP
    PERFORM politician_careers_sync(r.id, 'backfill:array');
    v_people := v_people + 1;
  END LOOP;
  RAISE NOTICE '學經歷回填：% 人，學歷 % 項、經歷 % 項', v_people,
    (SELECT count(*) FROM politician_careers WHERE kind = 'education'),
    (SELECT count(*) FROM politician_careers WHERE kind = 'career');
END $$;

-- 已落庫的 politician 交件，照落庫順序掛出處（跟之後的落庫觸發器同一條規則）
DO $$
DECLARE
  r RECORD;
  v_contribs INTEGER := 0;
BEGIN
  FOR r IN
    SELECT c.id, c.applied_politician_id, c.payload, c.source_urls, coalesce(c.applied_at, c.created_at) AS at
      FROM contributions c
     WHERE c.contribution_type = 'politician' AND c.status = 'applied' AND c.applied_politician_id IS NOT NULL
       AND (jsonb_typeof(c.payload -> 'education') = 'array' OR jsonb_typeof(c.payload -> 'experience') = 'array')
     ORDER BY coalesce(c.applied_at, c.created_at), c.id
  LOOP
    PERFORM politician_careers_attach_sources(r.applied_politician_id,
      contribution_career_items(r.payload, 'education'), contribution_career_items(r.payload, 'experience'),
      r.source_urls, 'backfill:contribution', r.at);
    v_contribs := v_contribs + 1;
  END LOOP;
  RAISE NOTICE '學經歷出處回填：看過 % 筆已落庫交件；有出處 % 項、待補出處 % 項', v_contribs,
    (SELECT count(*) FROM politician_careers c WHERE EXISTS (SELECT 1 FROM source_refs s WHERE s.target_table = 'politician_careers' AND s.target_id = c.id::TEXT)),
    (SELECT count(*) FROM politician_careers c WHERE NOT EXISTS (SELECT 1 FROM source_refs s WHERE s.target_table = 'politician_careers' AND s.target_id = c.id::TEXT));
END $$;

-- ------------------------------------------------------------
-- 6. 同步觸發器（回填之後才掛：回填自己跑 sync，不要被觸發器再跑一次）
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION politician_careers_sync_trg() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' OR NEW.education IS DISTINCT FROM OLD.education OR NEW.experience IS DISTINCT FROM OLD.experience THEN
    BEGIN
      PERFORM politician_careers_sync(NEW.id, 'array_sync');
    EXCEPTION WHEN OTHERS THEN
      -- 不擋人物的寫入（跟 #347 出處同步同一個做法）；漏掉的看 politician_careers_drift
      RAISE WARNING 'politician_careers_sync(%) 失敗：%', NEW.id, SQLERRM;
    END;
  END IF;
  RETURN NULL;
END;
$$;
DROP TRIGGER IF EXISTS trg_politician_careers_sync ON politicians;
CREATE TRIGGER trg_politician_careers_sync
  AFTER INSERT OR UPDATE OF education, experience ON politicians
  FOR EACH ROW EXECUTE FUNCTION politician_careers_sync_trg();

CREATE OR REPLACE FUNCTION contribution_applied_career_sources() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.contribution_type = 'politician' AND NEW.applied_politician_id IS NOT NULL
     AND (jsonb_typeof(NEW.payload -> 'education') = 'array' OR jsonb_typeof(NEW.payload -> 'experience') = 'array') THEN
    BEGIN
      PERFORM politician_careers_attach_sources(NEW.applied_politician_id,
        contribution_career_items(NEW.payload, 'education'), contribution_career_items(NEW.payload, 'experience'),
        NEW.source_urls, 'contribution', coalesce(NEW.applied_at, now()));
    EXCEPTION WHEN OTHERS THEN
      RAISE WARNING 'politician_careers_attach_sources（交件 %）失敗：%', NEW.id, SQLERRM;
    END;
  END IF;
  RETURN NULL;
END;
$$;
DROP TRIGGER IF EXISTS trg_contribution_applied_career_sources ON contributions;
CREATE TRIGGER trg_contribution_applied_career_sources
  AFTER UPDATE OF status ON contributions
  FOR EACH ROW WHEN (NEW.status = 'applied' AND OLD.status IS DISTINCT FROM 'applied')
  EXECUTE FUNCTION contribution_applied_career_sources();

-- ------------------------------------------------------------
-- 7. 讀取：一項一列＋它的出處；needs_source＝待補出處
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW politician_careers_full AS
SELECT c.id, c.politician_id, c.kind, c.text, c.start_year, c.end_year, c.sort_order,
       coalesce(s.sources, '[]'::JSONB) AS sources,
       (s.sources IS NULL) AS needs_source
  FROM politician_careers c
  LEFT JOIN LATERAL (
    SELECT jsonb_agg(jsonb_build_object('url', so.url, 'title', so.title, 'source_kind', so.source_kind,
                                        'archive_url', so.archive_url, 'role', r.role)
                     ORDER BY (r.role = 'primary') DESC, r.created_at, so.id) AS sources
      FROM source_refs r
      JOIN sources so ON so.id = r.source_id
     WHERE r.target_table = 'politician_careers' AND r.target_id = c.id::TEXT
  ) s ON true;
COMMENT ON VIEW politician_careers_full IS '學經歷一項一列＋出處（primary 在前）；needs_source＝true 就是「待補出處」（#346）';
ALTER VIEW politician_careers_full SET (security_invoker = on);
GRANT SELECT ON politician_careers_full TO anon, authenticated;

-- 陣列與表對不上的項目（正常是空的）：problem＝missing 陣列有、表沒有／extra 表有、陣列沒有
CREATE OR REPLACE VIEW politician_careers_drift AS
WITH want AS (
  SELECT p.id AS politician_id, w.kind, w.key
    FROM politicians p
    CROSS JOIN LATERAL politician_career_items(p.education, p.experience) w
), have AS (
  SELECT politician_id, kind, text_key AS key FROM politician_careers
)
SELECT politician_id, 'missing'::TEXT AS problem, kind, key FROM (SELECT * FROM want EXCEPT SELECT * FROM have) a
UNION ALL
SELECT politician_id, 'extra'::TEXT, kind, key FROM (SELECT * FROM have EXCEPT SELECT * FROM want) b;
COMMENT ON VIEW politician_careers_drift IS '陣列（politicians.education／experience）跟 politician_careers 對不上的項目，正常是空的（#346）';
ALTER VIEW politician_careers_drift SET (security_invoker = on);
GRANT SELECT ON politician_careers_drift TO anon, authenticated;

-- ------------------------------------------------------------
-- 8. 派工臂：沒有出處的學經歷 → profile_detail_gap（補學經歷條列），一個人一件
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION contribution_auto_tasks_career_sources()
RETURNS TABLE (task_id TEXT, task_type TEXT, target JSONB, what_we_need TEXT, hint_sources TEXT[], reward INTEGER, region TEXT)
LANGUAGE sql STABLE AS $$
  WITH unsourced AS (
    SELECT c.politician_id, c.kind, c.text, c.sort_order
      FROM politician_careers c
     WHERE NOT EXISTS (SELECT 1 FROM source_refs r WHERE r.target_table = 'politician_careers' AND r.target_id = c.id::TEXT)
  ),
  per AS (
    SELECT u.politician_id,
           coalesce(array_agg(u.text ORDER BY u.sort_order) FILTER (WHERE u.kind = 'education'), '{}'::TEXT[]) AS edu,
           coalesce(array_agg(u.text ORDER BY u.sort_order) FILTER (WHERE u.kind = 'career'), '{}'::TEXT[]) AS exp
      FROM unsourced u
     GROUP BY u.politician_id
  ),
  inflight AS (
    -- 已經有人交了學經歷、還在等票或自動重試中：先不派（被退件就會回來）
    SELECT DISTINCT coalesce(c.payload ->> 'politician_id', c.applied_politician_id::TEXT) AS pid
      FROM contributions c
     WHERE c.contribution_type = 'politician' AND c.status IN ('pending', 'verified', 'apply_failed')
       AND (c.payload ? 'education' OR c.payload ? 'experience')
  )
  SELECT 'auto:profile_detail_gap:sources:' || p.id, 'profile_detail_gap',
         jsonb_build_object('kind', 'career_sources', 'politician_id', p.id, 'name', p.name, 'party', p.party, 'region', p.region,
                            'unsourced_education', to_jsonb(x.edu), 'unsourced_experience', to_jsonb(x.exp)),
         '「' || p.name || '」的學經歷有 ' || (cardinality(x.edu) + cardinality(x.exp)) || ' 項還沒有出處（網站上標「待補出處」）：'
           || CASE WHEN cardinality(x.edu) > 0 THEN '學歷「' || array_to_string(x.edu, '」「') || '」' ELSE '' END
           || CASE WHEN cardinality(x.edu) > 0 AND cardinality(x.exp) > 0 THEN '；' ELSE '' END
           || CASE WHEN cardinality(x.exp) > 0 THEN '經歷「' || array_to_string(x.exp, '」「') || '」' ELSE '' END
           || '。請找看得到這幾項的頁面（議會、機關的個人介紹頁最常有，其次本人官網、維基百科、新聞報導），'
           || '用 politician 型別交一筆：politician_id 填 ' || p.id || '、education／experience 照上面的原文抄你查得到的那幾項（一條一項，字要一樣），'
           || 'source_urls 放那些頁面。伺服器只會把出處掛到文字相同的項目上；查到的寫法不一樣、或查到這裡沒有的項目，照抄這裡的原文並在 note 說明，不要改字。'
           || '**臉書、IG、Threads 讀不到，不算出處**。查不到就用 no_change 回報你查了哪裡。',
         ARRAY['議會官網的議員個人頁（學歷、經歷欄）', '縣市政府、機關的首長簡介頁（*.gov.tw）', '本人官網', 'zh.wikipedia.org'],
         1, p.region
    FROM per x
    JOIN politicians p ON p.id = x.politician_id AND p.merged_into IS NULL
   WHERE NOT EXISTS (SELECT 1 FROM inflight i WHERE i.pid = p.id::TEXT)
$$;
COMMENT ON FUNCTION contribution_auto_tasks_career_sources IS
  '學經歷沒有出處 → profile_detail_gap（target.kind＝career_sources），一個人一件；已有人交了學經歷在等票的先不派（#346，2026-10-06）';

-- 所有自動缺口：原樣保留 20261006034900（#349 政策脈絡）那一版的每一支臂，加學經歷補出處這一支
CREATE OR REPLACE FUNCTION contribution_auto_tasks_arms()
RETURNS TABLE (task_id TEXT, task_type TEXT, target JSONB, what_we_need TEXT, hint_sources TEXT[], reward INTEGER, region TEXT)
LANGUAGE sql STABLE AS $$
  WITH raw AS (SELECT * FROM contribution_auto_tasks_raw()),
       due AS (SELECT * FROM contribution_auto_tasks_deadline_due())
  SELECT r.task_id, r.task_type, r.target,
         r.what_we_need || CASE WHEN r.task_type = 'roster_check'
                                 AND r.target->>'election_type' IN ('鄉鎮市長', '鄉鎮市民代表', '直轄市山地原住民區長', '直轄市山地原住民區民代表')
                                THEN '【這種選舉】每筆 candidacy 都要填 sub_region＝候選人所在的鄉鎮市區（例：東港鎮、茂林區），不要只填縣市。'
                                ELSE '' END,
         r.hint_sources, r.reward, r.region
    FROM raw r
   WHERE (r.task_type <> 'roster_check' OR roster_scope_covers(r.target->>'election_type', r.region))
     AND NOT (r.task_type = 'progress_stale' AND EXISTS (SELECT 1 FROM due d WHERE d.target->>'policy_id' = r.target->>'policy_id'))
  UNION ALL SELECT * FROM contribution_auto_tasks_dup()
  UNION ALL SELECT * FROM contribution_auto_tasks_legacy()
  UNION ALL SELECT * FROM contribution_auto_tasks_mismatch()
  UNION ALL SELECT * FROM contribution_auto_tasks_policy_dup()
  UNION ALL SELECT * FROM contribution_auto_tasks_not_running()
  UNION ALL SELECT * FROM contribution_auto_tasks_mayor_policies()
  UNION ALL SELECT * FROM contribution_auto_tasks_term_policies()
  UNION ALL SELECT * FROM contribution_auto_tasks_roster_villages()
  UNION ALL SELECT * FROM contribution_auto_tasks_township_gap()
  UNION ALL SELECT * FROM contribution_auto_tasks_region_gap()
  UNION ALL SELECT * FROM contribution_auto_tasks_elected_missing()
  UNION ALL SELECT * FROM contribution_auto_tasks_roster_cec_gap()
  UNION ALL SELECT * FROM contribution_auto_tasks_district_seats()
  UNION ALL SELECT * FROM contribution_auto_tasks_policy_elements()
  UNION ALL SELECT * FROM due
  UNION ALL SELECT * FROM contribution_auto_tasks_lineage_candidates()
  UNION ALL SELECT * FROM contribution_auto_tasks_handover_missing()
  UNION ALL SELECT * FROM contribution_auto_tasks_lineage_roles()
  UNION ALL SELECT * FROM contribution_auto_tasks_lineage_links()
  UNION ALL SELECT * FROM contribution_auto_tasks_career_sources()
$$;
COMMENT ON FUNCTION contribution_auto_tasks_arms IS
  '所有自動缺口的來源，只有 UNION：新增任務型別只改這一支，派工規則（contribution_auto_tasks）不要再為此重寫。'
  '2026-10-06 加學經歷補出處（contribution_auto_tasks_career_sources，沿用 profile_detail_gap，#346）。';

-- ------------------------------------------------------------
-- 9. 自我檢查：回填完陣列與表要一致，不一致整支退回
-- ------------------------------------------------------------
DO $$
DECLARE v_drift INTEGER;
BEGIN
  SELECT count(*) INTO v_drift FROM politician_careers_drift;
  IF v_drift > 0 THEN
    RAISE EXCEPTION '學經歷回填後陣列與表有 % 項對不上（看 politician_careers_drift）', v_drift;
  END IF;
  RAISE NOTICE '學經歷補出處派工：上線當下 % 件', (SELECT count(*) FROM contribution_auto_tasks_career_sources());
END $$;
